// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconBulbSlash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M7.92239 4.00443C9.08394 3.21277 10.4868 2.75 12 2.75C16.0041 2.75 19.25 5.99594 19.25 10C19.25 11.3317 18.7489 12.5399 18.0452 13.5797C17.8131 13.9227 17.903 14.389 18.2461 14.6212C18.5891 14.8533 19.0554 14.7634 19.2875 14.4203C20.1026 13.2159 20.75 11.7185 20.75 10C20.75 5.16751 16.8325 1.25 12 1.25C10.176 1.25 8.48028 1.80893 7.07761 2.76493C6.73533 2.99822 6.64697 3.4648 6.88025 3.80707C7.11354 4.14935 7.58012 4.23771 7.92239 4.00443ZM3.53033 2.46967C3.23744 2.17678 2.76256 2.17678 2.46967 2.46967C2.17678 2.76256 2.17678 3.23744 2.46967 3.53033L4.47382 5.53448C3.69648 6.84207 3.25 8.36976 3.25 10C3.25 13.3097 5.72304 15.8581 7.22652 17.116C7.86169 17.6475 8.25 18.3764 8.25 19.1123C8.25 21.1214 9.87865 22.75 11.8877 22.75H12.1268C14.1278 22.75 15.75 21.1278 15.75 19.1268C15.75 18.5426 15.9975 17.9615 16.4195 17.4801L19.4697 20.5303C19.7626 20.8232 20.2374 20.8232 20.5303 20.5303C20.8232 20.2374 20.8232 19.7626 20.5303 19.4697L16.9678 15.9072L5.96206 4.9014L3.53033 2.46967Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconBulbSlash.isIcon = true;

export const IconBulbSlash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconBulbSlash);
