// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconHeadphones2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 1.25C7.71979 1.25 4.25 4.71979 4.25 9V12.2527C3.5604 12.2611 3.14152 12.2961 2.79329 12.4403C2.18072 12.694 1.69404 13.1807 1.4403 13.7933C1.25 14.2527 1.25 14.8351 1.25 16V19C1.25 20.1649 1.25 20.7473 1.4403 21.2067C1.69404 21.8193 2.18072 22.306 2.79329 22.5597C3.25272 22.75 3.83515 22.75 5 22.75C6.16485 22.75 6.74728 22.75 7.20671 22.5597C7.81928 22.306 8.30596 21.8193 8.5597 21.2067C8.75 20.7473 8.75 20.1649 8.75 19V16C8.75 14.8351 8.75 14.2527 8.5597 13.7933C8.30596 13.1807 7.81928 12.694 7.20671 12.4403C6.85848 12.2961 6.4396 12.2611 5.75 12.2527V9C5.75 5.54822 8.54822 2.75 12 2.75C15.4518 2.75 18.25 5.54822 18.25 9V12.2527C17.5604 12.2611 17.1415 12.2961 16.7933 12.4403C16.1807 12.694 15.694 13.1807 15.4403 13.7933C15.25 14.2527 15.25 14.8351 15.25 16V19C15.25 20.1649 15.25 20.7473 15.4403 21.2067C15.694 21.8193 16.1807 22.306 16.7933 22.5597C17.2527 22.75 17.8351 22.75 19 22.75C20.1649 22.75 20.7473 22.75 21.2067 22.5597C21.8193 22.306 22.306 21.8193 22.5597 21.2067C22.75 20.7473 22.75 20.1649 22.75 19V16C22.75 14.8351 22.75 14.2527 22.5597 13.7933C22.306 13.1807 21.8193 12.694 21.2067 12.4403C20.8585 12.2961 20.4396 12.2611 19.75 12.2527V9C19.75 4.71979 16.2802 1.25 12 1.25Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconHeadphones2.isIcon = true;

export const IconHeadphones2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconHeadphones2);
