// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconMouse(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 22.75C7.16751 22.75 3.25 18.8325 3.25 14V10C3.25 5.16751 7.16751 1.25 12 1.25V1.25C16.8325 1.25 20.75 5.16751 20.75 10V14C20.75 18.8325 16.8325 22.75 12 22.75V22.75ZM12 7C11.4477 7 11 7.44772 11 8V10C11 10.5523 11.4477 11 12 11V11C12.5523 11 13 10.5523 13 10V8C13 7.44772 12.5523 7 12 7V7Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconMouse.isIcon = true;

export const IconMouse = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconMouse);
