// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSmartphone(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M6.43404 1.68597C7.28968 1.25 8.40979 1.25 10.65 1.25H13.35C15.5902 1.25 16.7103 1.25 17.566 1.68597C18.3186 2.06947 18.9305 2.68139 19.314 3.43404C19.75 4.28968 19.75 5.40979 19.75 7.65V16.35C19.75 18.5902 19.75 19.7103 19.314 20.566C18.9305 21.3186 18.3186 21.9305 17.566 22.314C16.7103 22.75 15.5902 22.75 13.35 22.75H10.65C8.40979 22.75 7.28968 22.75 6.43404 22.314C5.68139 21.9305 5.06947 21.3186 4.68597 20.566C4.25 19.7103 4.25 18.5902 4.25 16.35V7.65C4.25 5.40979 4.25 4.28968 4.68597 3.43404C5.06947 2.68139 5.68139 2.06947 6.43404 1.68597ZM12 4.75C11.3096 4.75 10.75 5.30964 10.75 6C10.75 6.69036 11.3096 7.25 12 7.25C12.6904 7.25 13.25 6.69036 13.25 6C13.25 5.30964 12.6904 4.75 12 4.75ZM10 18.25C9.58579 18.25 9.25 18.5858 9.25 19C9.25 19.4142 9.58579 19.75 10 19.75H14C14.4142 19.75 14.75 19.4142 14.75 19C14.75 18.5858 14.4142 18.25 14 18.25H10Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconSmartphone.isIcon = true;

export const IconSmartphone = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSmartphone);
