// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconModules(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M5 2a3 3 0 100 6 3 3 0 000-6zm14 0a3 3 0 100 6 3 3 0 000-6zM2 19a3 3 0 116 0 3 3 0 01-6 0zm17-3a3 3 0 100 6 3 3 0 000-6z"
        fillRule="evenodd"
        opacity=".12"
      />
      <path
        d="M1.25 5a3.75 3.75 0 017.425-.75H12a.75.75 0 010 1.5H8.675A3.751 3.751 0 011.25 5zM5 2.75a2.25 2.25 0 110 4.5 2.25 2.25 0 010-4.5zM5.75 12a.75.75 0 00-1.5 0v3.325A3.751 3.751 0 005 22.75a3.75 3.75 0 00.75-7.425V12zm14-3.325A3.751 3.751 0 0019 1.25a3.75 3.75 0 00-.75 7.425V12a.75.75 0 001.5 0V8.675zM19 7.25a2.25 2.25 0 110-4.5 2.25 2.25 0 010 4.5zm-7 11a.75.75 0 000 1.5h3.325A3.751 3.751 0 0022.75 19a3.75 3.75 0 00-7.425-.75H12zm4.75.75a2.25 2.25 0 104.5 0 2.25 2.25 0 00-4.5 0zM5 16.75a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconModules.isIcon = true;

export const IconModules = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconModules);
