// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconBell(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M4.088 7.736a8.069 8.069 0 0115.824 0l1.254 6.27c.403 2.013-.666 4.037-2.534 4.867-.681.303-1.381.557-2.093.761l-.104.234a4.853 4.853 0 01-8.87 0l-.104-.234a16.1 16.1 0 01-2.093-.761c-1.868-.83-2.937-2.854-2.534-4.868l1.254-6.269zm5.36 12.337a3.353 3.353 0 005.103 0 16.53 16.53 0 01-5.102 0z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconBell.isIcon = true;

export const IconBell = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconBell);
