// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconFlag2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconFlag2(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M5.75 2a.75.75 0 00-1.5 0v20a.75.75 0 001.5 0v-6.414l.751-.188a5.92 5.92 0 014.482.667 7.42 7.42 0 006.165.676l3.09-1.03A.75.75 0 0020.75 15V4a.75.75 0 00-.987-.712l-3.09 1.03a5.92 5.92 0 01-4.918-.54 7.42 7.42 0 00-5.617-.835l-.388.096V2z"
        fillRule="evenodd"
      />
    </svg>
  );
});
