// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconMic = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  function IconMic(props) {
    return (
      <svg
        height="24"
        width="24"
        fill="currentColor"
        viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
        ref={props.ref}
        {...props}
      >
        <path
          d="M6.25 7a5.75 5.75 0 1111.5 0v4a5.75 5.75 0 01-11.5 0V7zm-1.5 4a.75.75 0 00-1.5 0c0 2.748 1.261 4.944 2.97 6.44 1.477 1.291 3.316 2.086 5.03 2.27V22a.75.75 0 001.5 0v-2.29c1.714-.184 3.553-.979 5.03-2.27 1.709-1.496 2.97-3.692 2.97-6.44a.75.75 0 00-1.5 0c0 2.252-1.024 4.056-2.458 5.31-1.448 1.268-3.277 1.94-4.792 1.94-1.515 0-3.344-.672-4.792-1.94C5.774 15.057 4.75 13.253 4.75 11z"
          fillRule="evenodd"
        />
      </svg>
    );
  },
);
