// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconMoreHoriz(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M4.5 9.5A2.507 2.507 0 002 12c0 1.375 1.125 2.5 2.5 2.5S7 13.375 7 12 5.875 9.5 4.5 9.5zm15 0A2.507 2.507 0 0017 12c0 1.375 1.125 2.5 2.5 2.5S22 13.375 22 12s-1.125-2.5-2.5-2.5zM9.5 12c0-1.375 1.125-2.5 2.5-2.5s2.5 1.125 2.5 2.5-1.125 2.5-2.5 2.5A2.507 2.507 0 019.5 12z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconMoreHoriz.isIcon = true;

export const IconMoreHoriz = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconMoreHoriz);
