// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconMouse = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconMouse(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M3.25 10a8.75 8.75 0 0117.5 0v4a8.75 8.75 0 11-17.5 0v-4zm9.5-2a.75.75 0 00-1.5 0v2a.75.75 0 001.5 0V8z"
        fillRule="evenodd"
      />
    </svg>
  );
});
