// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconPin(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2.25 10.5c0-5.47 4.393-9.25 9.75-9.25s9.75 3.78 9.75 9.25c0 4.17-1.866 7.233-3.984 9.239a13.29 13.29 0 01-3.183 2.24c-.976.484-1.912.77-2.583.77-.67 0-1.607-.286-2.583-.77a13.29 13.29 0 01-3.183-2.24C4.116 17.733 2.25 14.671 2.25 10.5zM12 14a3 3 0 100-6 3 3 0 000 6z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconPin.isIcon = true;

export const IconPin = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  _IconPin,
);
