// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconPlusRec = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconPlusRec(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M11.566 1.25H12.434c1.651 0 2.937 0 3.968.084 1.047.086 1.897.262 2.662.652a6.75 6.75 0 012.95 2.95c.39.765.566 1.615.652 2.662.084 1.031.084 2.317.084 3.968V12.434c0 1.651 0 2.937-.084 3.968-.086 1.047-.262 1.897-.652 2.662a6.75 6.75 0 01-2.95 2.95c-.765.39-1.615.566-2.662.652-1.031.084-2.317.084-3.968.084H11.566c-1.651 0-2.937 0-3.968-.084-1.047-.086-1.897-.262-2.662-.652a6.75 6.75 0 01-2.95-2.95c-.39-.765-.566-1.615-.652-2.662-.084-1.031-.084-2.317-.084-3.968V11.566c0-1.651 0-2.937.084-3.968.086-1.047.262-1.897.652-2.662a6.75 6.75 0 012.95-2.95c.765-.39 1.615-.566 2.662-.652 1.031-.084 2.317-.084 3.968-.084zM12.75 8a.75.75 0 00-1.5 0v3.25H8a.75.75 0 000 1.5h3.25V16a.75.75 0 001.5 0v-3.25H16a.75.75 0 000-1.5h-3.25V8z"
        fillRule="evenodd"
      />
    </svg>
  );
});
