// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconUserPlus(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M4.25 6a4.75 4.75 0 119.5 0 4.75 4.75 0 01-9.5 0zm16.5 1a.75.75 0 00-1.5 0v2.25H17a.75.75 0 000 1.5h2.25V13a.75.75 0 001.5 0v-2.25H23a.75.75 0 000-1.5h-2.25V7zM6.8 13.25a5.55 5.55 0 00-5.55 5.55 3.95 3.95 0 003.95 3.95h7.6a3.95 3.95 0 003.95-3.95 5.55 5.55 0 00-5.55-5.55H6.8z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconUserPlus.isIcon = true;

export const IconUserPlus = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconUserPlus);
