// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconWebcam = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconWebcam(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M12 1.25a8.75 8.75 0 100 17.5 8.75 8.75 0 000-17.5zM12 12a2 2 0 100-4 2 2 0 000 4zm-6.78 5.688a13.62 13.62 0 00-.507.776c-.312.523-.552 1.055-.534 1.622a2.75 2.75 0 001.063 2.087c.447.347 1.019.466 1.625.521.609.056 1.397.056 2.378.056h5.51c.98 0 1.77 0 2.378-.056.606-.055 1.178-.174 1.625-.521a2.75 2.75 0 001.063-2.087c.018-.567-.222-1.099-.534-1.622-.14-.235-.31-.492-.507-.776A10.211 10.211 0 0112 20.25c-2.6 0-4.973-.968-6.78-2.562z"
        fillRule="evenodd"
      />
    </svg>
  );
});
