[build]
  command = "pnpm run build --filter=mission-page"
  publish = "apps/mission/.next"
  functions = "apps/mission/netlify/functions"
  framework = "next"

[[plugins]]
  package = "@netlify/plugin-nextjs"