// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./notebook.tsx";
export * from "./note.tsx";
export * from "./note-text.tsx";
export * from "./note-2.tsx";
export * from "./note-2-text.tsx";
export * from "./folder.tsx";
export * from "./folder-upload.tsx";
export * from "./folder-slash.tsx";
export * from "./folder-plus.tsx";
export * from "./folder-photo.tsx";
export * from "./folder-open.tsx";
export * from "./folder-music.tsx";
export * from "./folder-move.tsx";
export * from "./folder-minus.tsx";
export * from "./folder-heart.tsx";
export * from "./folder-download.tsx";
export * from "./folder-cross.tsx";
export * from "./folder-compressed.tsx";
export * from "./folder-cloud.tsx";
export * from "./folder-check.tsx";
export * from "./file.tsx";
export * from "./file-upload.tsx";
export * from "./file-text.tsx";
export * from "./file-slash.tsx";
export * from "./file-shredder.tsx";
export * from "./file-scan.tsx";
export * from "./file-plus.tsx";
export * from "./file-move.tsx";
export * from "./file-minus.tsx";
export * from "./file-invoice.tsx";
export * from "./file-heart.tsx";
export * from "./file-draft.tsx";
export * from "./file-download.tsx";
export * from "./file-cross.tsx";
export * from "./file-code.tsx";
export * from "./file-check.tsx";
export * from "./file-agreement.tsx";
export * from "./clipboard.tsx";
export * from "./clipboard-text.tsx";
export * from "./clipboard-slash.tsx";
export * from "./clipboard-plus.tsx";
export * from "./clipboard-minus.tsx";
export * from "./clipboard-cross.tsx";
export * from "./clipboard-check.tsx";
