// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconBookQueue(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M6 7H12M6 11H12M6 15H8M19 6V18M22 8V16M8.4 22H9.6C11.8402 22 12.9603 22 13.816 21.564C14.5686 21.1805 15.1805 20.5686 15.564 19.816C16 18.9603 16 17.8402 16 15.6V8.4C16 6.15979 16 5.03968 15.564 4.18404C15.1805 3.43139 14.5686 2.81947 13.816 2.43597C12.9603 2 11.8402 2 9.6 2H8.4C6.15979 2 5.03968 2 4.18404 2.43597C3.43139 2.81947 2.81947 3.43139 2.43597 4.18404C2 5.03968 2 6.15979 2 8.4V15.6C2 17.8402 2 18.9603 2.43597 19.816C2.81947 20.5686 3.43139 21.1805 4.18404 21.564C5.03968 22 6.15979 22 8.4 22Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconBookQueue.isIcon = true;

export const IconBookQueue = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconBookQueue);
