// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconCd(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M11.9998 5.99979C15.3135 5.99979 17.9998 8.68608 17.9998 11.9998M21.9998 11.9998C21.9998 17.5226 17.5226 21.9998 11.9998 21.9998C6.47691 21.9998 1.99976 17.5226 1.99976 11.9998C1.99976 6.47694 6.47691 1.99979 11.9998 1.99979C17.5226 1.99979 21.9998 6.47694 21.9998 11.9998ZM13.9998 11.9998C13.9998 13.1044 13.1043 13.9998 11.9998 13.9998C10.8952 13.9998 9.99976 13.1044 9.99976 11.9998C9.99976 10.8952 10.8952 9.99979 11.9998 9.99979C13.1043 9.99979 13.9998 10.8952 13.9998 11.9998Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconCd.isIcon = true;

export const IconCd = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  _IconCd,
);
