// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconPlayPrevious(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M4 5L4 19M11.1872 14.6918L16.0696 17.8304C17.6755 18.8628 18.4785 19.379 19.1425 19.3316C19.7211 19.2903 20.2534 18.9997 20.601 18.5353C21 18.0024 21 17.0478 21 15.1387V8.86133C21 6.95219 21 5.99762 20.601 5.46471C20.2534 5.0003 19.7211 4.70974 19.1425 4.66841C18.4785 4.62099 17.6755 5.13718 16.0696 6.16956L11.1872 9.30823C9.79366 10.2041 9.09688 10.652 8.85622 11.2216C8.64595 11.7192 8.64595 12.2808 8.85622 12.7784C9.09688 13.348 9.79366 13.7959 11.1872 14.6918Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconPlayPrevious.isIcon = true;

export const IconPlayPrevious = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconPlayPrevious);
