// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconPlaylistPlay(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 4H20M2 9H16M2 14H11M2 19H9M21.0015 17.6656L17.2438 20.1708C16.8397 20.4402 16.6377 20.5749 16.4702 20.5649C16.3243 20.5561 16.1894 20.484 16.1012 20.3674C16 20.2336 16 19.9908 16 19.5052V14.4948C16 14.0092 16 13.7664 16.1012 13.6326C16.1894 13.516 16.3243 13.4439 16.4702 13.4351C16.6377 13.4251 16.8397 13.5598 17.2438 13.8292L21.0015 16.3344C21.3354 16.5569 21.5023 16.6682 21.5605 16.8085C21.6113 16.9311 21.6113 17.0689 21.5605 17.1915C21.5023 17.3318 21.3354 17.4431 21.0015 17.6656Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconPlaylistPlay.isIcon = true;

export const IconPlaylistPlay = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconPlaylistPlay);
