// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconShuffle(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 20H4.25227C5.59228 20 6.26228 20 6.81969 19.7658C7.31151 19.5592 7.73933 19.2251 8.05907 18.7981C8.42146 18.3142 8.58396 17.6642 8.90896 16.3642L11.091 7.63583C11.416 6.33583 11.5785 5.68584 11.9409 5.20187C12.2607 4.77485 12.6885 4.44082 13.1803 4.23419C13.7377 4 14.4077 4 15.7477 4H22M22 4L19 1M22 4L19 7M2 4H8M22 20L19 23M22 20L19 17M22 20H12"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconShuffle.isIcon = true;

export const IconShuffle = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconShuffle);
