// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./youtube.tsx";
export * from "./windows.tsx";
export * from "./twitter.tsx";
export * from "./spotify.tsx";
export * from "./soundcloud.tsx";
export * from "./sketch.tsx";
export * from "./producthunt.tsx";
export * from "./pinterest.tsx";
export * from "./photoshop.tsx";
export * from "./notion.tsx";
export * from "./messanger.tsx";
export * from "./linkedin.tsx";
export * from "./instagram.tsx";
export * from "./illustrator.tsx";
export * from "./googleplay.tsx";
export * from "./github.tsx";
export * from "./framer.tsx";
export * from "./figma.tsx";
export * from "./facebook.tsx";
export * from "./dribbble.tsx";
export * from "./behance.tsx";
export * from "./appstore.tsx";
export * from "./apple.tsx";
export * from "./android.tsx";
