// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconBell(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M16.305 18.315a.75.75 0 01.38.99l-.25.563a4.853 4.853 0 01-8.87 0l-.25-.563a.75.75 0 111.37-.61l.25.564a3.353 3.353 0 006.13 0l.25-.564a.75.75 0 01.99-.38z"
        fillRule="evenodd"
        opacity=".4"
      />
      <path
        d="M4.088 7.736a8.069 8.069 0 0115.824 0l1.254 6.27c.403 2.013-.666 4.037-2.534 4.867a16.43 16.43 0 01-13.264 0c-1.868-.83-2.937-2.854-2.534-4.868l1.254-6.269zM12 2.75a6.569 6.569 0 00-6.441 5.28L4.305 14.3a2.9 2.9 0 001.672 3.202 14.93 14.93 0 0012.046 0 2.9 2.9 0 001.672-3.202l-1.254-6.27A6.569 6.569 0 0012 2.75z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconBell.isIcon = true;

export const IconBell = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconBell);
