// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconCompass = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconCompass(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M16.53 7.47a.75.75 0 01.153.84l-2.004 4.408-.027.06c-.157.346-.28.619-.46.858a2.75 2.75 0 01-.556.556c-.24.18-.512.303-.858.46l-.06.027-4.408 2.004a.75.75 0 01-.993-.993l2.004-4.408.027-.06c.157-.346.28-.619.46-.858.158-.211.345-.398.556-.556.24-.18.512-.303.858-.46l.06-.027 4.408-2.004a.75.75 0 01.84.153zm-2.04 2.04l-2.587 1.176c-.434.197-.548.254-.641.323a1.251 1.251 0 00-.253.253c-.07.093-.126.207-.323.64L9.51 14.49l2.587-1.176c.434-.197.548-.254.641-.323.096-.072.181-.157.253-.253.07-.093.126-.207.323-.64L14.49 9.51z"
        fillRule="evenodd"
        opacity=".4"
      />
      <path
        d="M12 2.75a9.25 9.25 0 100 18.5 9.25 9.25 0 000-18.5zM1.25 12C1.25 6.063 6.063 1.25 12 1.25S22.75 6.063 22.75 12 17.937 22.75 12 22.75 1.25 17.937 1.25 12z"
        fillRule="evenodd"
      />
    </svg>
  );
});
