// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconEmotionSmile = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconEmotionSmile(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M10 10a1 1 0 11-2 0 1 1 0 012 0zm-2.45 4.4a.75.75 0 011.05.15 4.243 4.243 0 003.4 1.7c1.39 0 2.624-.666 3.4-1.7a.75.75 0 011.2.9 5.742 5.742 0 01-4.6 2.3 5.742 5.742 0 01-4.6-2.3.75.75 0 01.15-1.05zM15 11a1 1 0 100-2 1 1 0 000 2z"
        fillRule="evenodd"
        opacity=".4"
      />
      <path
        d="M1.25 12C1.25 6.063 6.063 1.25 12 1.25S22.75 6.063 22.75 12 17.937 22.75 12 22.75 1.25 17.937 1.25 12zM12 2.75a9.25 9.25 0 100 18.5 9.25 9.25 0 000-18.5z"
        fillRule="evenodd"
      />
    </svg>
  );
});
