// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFlag2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M10.983 5.065a5.92 5.92 0 00-4.482-.667l-1.319.33a.75.75 0 01-.364-1.456l1.32-.33a7.42 7.42 0 015.617.836 5.92 5.92 0 004.918.54l3.09-1.03A.75.75 0 0120.75 4v11a.75.75 0 01-.513.711l-3.09 1.03a7.42 7.42 0 01-6.164-.676 5.92 5.92 0 00-4.482-.667l-1.319.33a.75.75 0 11-.364-1.456l1.32-.33a7.42 7.42 0 015.617.836 5.92 5.92 0 004.918.54l2.577-.859V5.041l-2.102.7a7.42 7.42 0 01-6.165-.676z"
        fillRule="evenodd"
        opacity=".4"
      />
      <path
        d="M5 1.25a.75.75 0 01.75.75v20a.75.75 0 01-1.5 0V2A.75.75 0 015 1.25z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconFlag2.isIcon = true;

export const IconFlag2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFlag2);
