// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconLifebuoy = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconLifebuoy(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M5.46 4.399a.75.75 0 10-1.061 1.06l3.754 3.754A4.729 4.729 0 007.25 12c0 1.041.335 2.004.903 2.787L4.399 18.54a.75.75 0 101.06 1.06l3.754-3.754A4.729 4.729 0 0012 16.75a4.728 4.728 0 002.787-.903l3.754 3.754a.75.75 0 101.06-1.06l-3.754-3.755A4.728 4.728 0 0016.75 12a4.729 4.729 0 00-.903-2.787l3.754-3.754a.75.75 0 00-1.06-1.06l-3.754 3.754A4.729 4.729 0 0012 7.25a4.729 4.729 0 00-2.787.903L5.46 4.399zM8.75 12a3.25 3.25 0 116.5 0 3.25 3.25 0 01-6.5 0z"
        fillRule="evenodd"
        opacity=".4"
      />
      <path
        d="M12 2.75a9.25 9.25 0 100 18.5 9.25 9.25 0 000-18.5zM1.25 12C1.25 6.063 6.063 1.25 12 1.25S22.75 6.063 22.75 12 17.937 22.75 12 22.75 1.25 17.937 1.25 12z"
        fillRule="evenodd"
      />
    </svg>
  );
});
