// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconMic(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M4 10.25a.75.75 0 01.75.75c0 2.252 1.024 4.056 2.458 5.31 1.448 1.268 3.277 1.94 4.792 1.94 1.515 0 3.344-.672 4.792-1.94 1.434-1.254 2.458-3.058 2.458-5.31a.75.75 0 011.5 0c0 2.748-1.261 4.944-2.97 6.44-1.477 1.291-3.316 2.086-5.03 2.27V22a.75.75 0 01-1.5 0v-2.29c-1.714-.184-3.553-.979-5.03-2.27-1.709-1.496-2.97-3.692-2.97-6.44a.75.75 0 01.75-.75z"
        fillRule="evenodd"
        opacity=".4"
      />
      <path
        d="M6.25 7a5.75 5.75 0 1111.5 0v4a5.75 5.75 0 01-11.5 0V7zM12 2.75A4.25 4.25 0 007.75 7v4a4.25 4.25 0 008.5 0V7A4.25 4.25 0 0012 2.75z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconMic.isIcon = true;

export const IconMic = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  _IconMic,
);
