// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconSearch = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconSearch(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M16.97 16.97a.75.75 0 011.06 0l3.5 3.5a.75.75 0 11-1.06 1.06l-3.5-3.5a.75.75 0 010-1.06z"
        fillRule="evenodd"
        opacity=".4"
      />
      <path
        d="M11 2.75a8.25 8.25 0 100 16.5 8.25 8.25 0 000-16.5zM1.25 11c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S1.25 16.385 1.25 11z"
        fillRule="evenodd"
      />
    </svg>
  );
});
