// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconUsers(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M15 1.25a.75.75 0 000 1.5 3.25 3.25 0 010 6.5.75.75 0 000 1.5 4.75 4.75 0 100-9.5zm2 12a.75.75 0 000 1.5h1.2a4.05 4.05 0 014.05 4.05 2.45 2.45 0 01-2.45 2.45H17a.75.75 0 000 1.5h2.8a3.95 3.95 0 003.95-3.95 5.55 5.55 0 00-5.55-5.55H17z"
        fillRule="evenodd"
        opacity=".4"
      />
      <path
        d="M4.75 6a3.25 3.25 0 116.5 0 3.25 3.25 0 01-6.5 0zM8 1.25a4.75 4.75 0 100 9.5 4.75 4.75 0 000-9.5zm-2.2 12A5.55 5.55 0 00.25 18.8a3.95 3.95 0 003.95 3.95h7.6a3.95 3.95 0 003.95-3.95 5.55 5.55 0 00-5.55-5.55H5.8zM1.75 18.8a4.05 4.05 0 014.05-4.05h4.4a4.05 4.05 0 014.05 4.05 2.45 2.45 0 01-2.45 2.45H4.2a2.45 2.45 0 01-2.45-2.45z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconUsers.isIcon = true;

export const IconUsers = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconUsers);
