// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconEvmosCirc(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <rect height="24" width="24" fill="#D04B00" rx="12" />
      <path
        d="M10 6.4C6.8 7.7 6.5 11 5.5 12.5s-3.3 2.5-3 3.2 2.6 0 4.3.5c1.8.5 4.2 2.7 7.6 1.4a6 6 0 0 0 3.5-3.6l-.1-.3h-.4a5 5 0 0 1-3.6 2.7 5 5 0 0 1-5-2.7l-.1-.3-.2-.4a57 57 0 0 1 9-3.2h.3v.2l.4 1 .3.1 1.3-.7Q22 9 21.9 8.3q-.4-.6-3-.2l-1.8.4-.3.1a42 42 0 0 0-8.5 3 5 5 0 0 1 2.1-3.9 5 5 0 0 1 4.5-.5h.3v-.3l-.1-.2a6 6 0 0 0-5-.3"
        fill="#FFDBCE"
      />
    </svg>
  );
}

_IconEvmosCirc.isIcon = true;

export const IconEvmosCirc = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconEvmosCirc);
