// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconCameraSlash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M5.33333 5.33309C6.32099 5.13556 7.31388 4.52894 7.87258 3.69088C8.57693 2.63436 9.7627 1.99976 11.0325 1.99976H12.9675C14.2373 1.99976 15.4231 2.63436 16.1274 3.69088C16.7223 4.58317 17.6399 5.12773 18.6783 5.33542C20.6097 5.7217 22 7.41756 22 9.38722V13.2076C22 16.7589 22 18.5346 21.1389 19.8051C20.9609 20.0676 20.7588 20.312 20.5355 20.5353M5.33333 5.33309L2 1.99976M5.33333 5.33309L20.5355 20.5353M22.5 22.4998L20.5355 20.5353M17 21.9243C16.012 21.9998 14.785 21.9998 13.2078 21.9998H10.7922C7.24083 21.9998 5.46517 21.9998 4.19468 21.1386C3.6696 20.7827 3.21704 20.3302 2.86114 19.8051C2 18.5346 2 16.7589 2 13.2076V9.38722C2 8.50558 2.27855 7.67879 2.75949 6.99976M9.71586 9.71586C10.3635 9.26461 11.1508 9 12 9C14.2091 9 16 10.7909 16 13C16 13.8492 15.7354 14.6365 15.2841 15.2841M8.12602 12C8.04375 12.3196 8 12.6547 8 13C8 15.2091 9.79086 17 12 17C12.3453 17 12.6804 16.9562 13 16.874"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconCameraSlash.isIcon = true;

export const IconCameraSlash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconCameraSlash);
