// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconImageEdit(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 2H11.5V2C8.234 2 6.601 2 5.34627 2.61876C4.16167 3.20294 3.20294 4.16167 2.61876 5.34627C2 6.601 2 8.234 2 11.5V12.4C2 15.7603 2 17.4405 2.65396 18.7239C3.2292 19.8529 4.14708 20.7708 5.27606 21.346C6.55953 22 8.23969 22 11.6 22H12.5C15.766 22 17.399 22 18.6537 21.3812C19.8383 20.7971 20.7971 19.8383 21.3812 18.6537C22 17.399 22 15.766 22 12.5V12.5V12M21.5 17.6875L20.0752 16.2627C19.2832 15.4707 18.8872 15.0747 18.4305 14.9263C18.0289 14.7958 17.5962 14.7958 17.1945 14.9263C16.7378 15.0747 16.3418 15.4707 15.5498 16.2627L14.4861 17.3264M2.5 18.5L6.77044 14.2296C7.55197 13.448 7.94273 13.0573 8.39428 12.9083C8.79155 12.7773 9.21991 12.7741 9.61907 12.8993C10.0728 13.0415 10.4693 13.4265 11.2623 14.1964L14.4861 17.3264M14.4861 17.3264L18.5 21.3403M14 10L14.12 9.40013C14.2612 8.69387 14.3319 8.34073 14.461 8.01144C14.5757 7.71916 14.7243 7.44139 14.9039 7.18387C15.1063 6.89374 15.3609 6.63909 15.8702 6.1298L18 4C18.5523 3.44771 19.4477 3.44772 20 4V4C20.5523 4.55228 20.5523 5.44771 20 6L17.8702 8.12979C17.3609 8.63909 17.1063 8.89374 16.8161 9.09608C16.5586 9.27568 16.2808 9.42434 15.9886 9.53899C15.6593 9.66815 15.3061 9.73877 14.5999 9.88003L14 10Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconImageEdit.isIcon = true;

export const IconImageEdit = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconImageEdit);
