// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconGlassWine(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2.25 2.86111C2.25 1.97132 2.97132 1.25 3.86111 1.25L20.1389 1.25001C21.0287 1.25001 21.75 1.97133 21.75 2.86112L21.75 6.00001C21.75 11.1325 17.7842 15.3387 12.7498 15.7216L12.7498 21.2499L15.9998 21.2499C16.414 21.2499 16.7498 21.5857 16.7498 21.9999C16.7498 22.4142 16.414 22.7499 15.9998 22.7499L11.9998 22.7499L7.99978 22.7499C7.58557 22.7499 7.24978 22.4142 7.24978 21.9999C7.24978 21.5857 7.58557 21.2499 7.99978 21.2499L11.2498 21.2499L11.2498 15.7216C6.21555 15.3385 2.25 11.1324 2.25 6L2.25 2.86111Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconGlassWine.isIcon = true;

export const IconGlassWine = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconGlassWine);
