// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFingerprint2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M22 12C22 6.47715 17.5228 2 12 2C10.5778 2 9.22492 2.2969 8 2.83209M3.99927 6C2.74389 7.67132 2 9.74879 2 12C2 16.8379 5.43552 20.8734 10 21.8M20.6622 17C19.2531 19.4359 16.846 21.2223 14 21.8M12 6C8.68629 6 6 8.68629 6 12C6 13.2267 6.36815 14.3675 7 15.3178M16 7.52779C17.2275 8.62643 18 10.223 18 12C18 15.3137 15.3137 18 12 18C11.2987 18 10.6256 17.8797 10 17.6586M12 10V14"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconFingerprint2.isIcon = true;

export const IconFingerprint2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFingerprint2);
