// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconAtom(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12.0001 12.0001H12.0101M16.2427 7.7571C20.929 12.4434 22.8285 18.1419 20.4854 20.485C18.1422 22.8282 12.4437 20.9287 7.75743 16.2424C3.07114 11.5561 1.17165 5.85761 3.51479 3.51446C5.85794 1.17132 11.5564 3.07081 16.2427 7.7571ZM16.2427 16.2424C11.5564 20.9287 5.85796 22.8282 3.51481 20.4851C1.17166 18.1419 3.07116 12.4434 7.75745 7.75716C12.4437 3.07087 18.1422 1.17137 20.4854 3.51452C22.8285 5.85766 20.929 11.5561 16.2427 16.2424ZM12.5001 12.0001C12.5001 12.2762 12.2762 12.5001 12.0001 12.5001C11.7239 12.5001 11.5001 12.2762 11.5001 12.0001C11.5001 11.7239 11.7239 11.5001 12.0001 11.5001C12.2762 11.5001 12.5001 11.7239 12.5001 12.0001Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconAtom.isIcon = true;

export const IconAtom = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconAtom);
