// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconAward(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M6.99987 16.5001L5.99988 22.0001C7.98179 21.6698 9.98438 21.2208 11.9999 21.2208C14.0154 21.2208 16.018 21.6698 17.9999 22.0001L16.9999 16.5001M11.9999 18.0001C7.5816 18.0001 3.99988 14.4184 3.99988 10.0001C3.99988 5.58184 7.5816 2.00012 11.9999 2.00012C16.4182 2.00012 19.9999 5.58184 19.9999 10.0001C19.9999 14.4184 16.4182 18.0001 11.9999 18.0001Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconAward.isIcon = true;

export const IconAward = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconAward);
