// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconBluetoothRec(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M10.8462 12V7.75068C10.8462 6.84711 10.8462 6.39533 11.036 6.13296C11.2016 5.90409 11.4563 5.75594 11.7371 5.72514C12.059 5.68983 12.4517 5.91318 13.2372 6.35989L13.332 6.41381C14.5333 7.09706 15.1339 7.43868 15.3346 7.88635C15.5097 8.27673 15.5097 8.72327 15.3346 9.11365C15.1339 9.56132 14.5333 9.90294 13.332 10.5862L10.8462 12ZM10.8462 12V16.2493C10.8462 17.1529 10.8462 17.6047 11.036 17.867C11.2016 18.0959 11.4563 18.2441 11.7371 18.2749C12.059 18.3102 12.4517 18.0868 13.2372 17.6401L13.332 17.5862C14.5333 16.9029 15.1339 16.5613 15.3346 16.1137C15.5097 15.7233 15.5097 15.2767 15.3346 14.8863C15.1339 14.4387 14.5333 14.0971 13.332 13.4138L10.8462 12ZM10.8462 12L7 10.0909M10.8462 12L7 14.5455M11.6 22H12.4C15.7603 22 17.4405 22 18.7239 21.346C19.8529 20.7708 20.7708 19.8529 21.346 18.7239C22 17.4405 22 15.7603 22 12.4V11.6C22 8.23969 22 6.55953 21.346 5.27606C20.7708 4.14708 19.8529 3.2292 18.7239 2.65396C17.4405 2 15.7603 2 12.4 2H11.6C8.23969 2 6.55953 2 5.27606 2.65396C4.14708 3.2292 3.2292 4.14708 2.65396 5.27606C2 6.55953 2 8.23969 2 11.6V12.4C2 15.7603 2 17.4405 2.65396 18.7239C3.2292 19.8529 4.14708 20.7708 5.27606 21.346C6.55953 22 8.23969 22 11.6 22Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconBluetoothRec.isIcon = true;

export const IconBluetoothRec = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconBluetoothRec);
