// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconBookmarkSlash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M6.73005 2.54497C7.79961 2 9.19974 2 12 2C14.8003 2 16.2004 2 17.27 2.54497C18.2108 3.02433 18.9757 3.78924 19.455 4.73005C20 5.79961 20 7.19974 20 10V14M2 4L4.19751 5.75801M22 20L20 18.4M20 18.4V22L19.1554 21.5777C15.6442 19.8221 13.8885 18.9443 12 18.9443C10.1115 18.9443 8.35582 19.8221 4.84458 21.5777L4 22V10C4 8.00348 4 6.7187 4.19751 5.75801M20 18.4L4.19751 5.75801"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconBookmarkSlash.isIcon = true;

export const IconBookmarkSlash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconBookmarkSlash);
