// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconCopyright(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M15 9.59961C14.7788 9.29674 14.5167 9.02722 14.2222 8.79971C13.5723 8.29756 12.7644 8 11.8889 8C9.74112 8 8 9.79086 8 12C8 14.2091 9.74112 16 11.8889 16C12.7644 16 13.5723 15.7024 14.2222 15.2003C14.5167 14.9728 14.7788 14.7033 15 14.4004M12 22V22C17.5228 22 22 17.5228 22 12V12C22 6.47715 17.5228 2 12 2V2C6.47715 2 2 6.47715 2 12V12C2 17.5228 6.47715 22 12 22Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconCopyright.isIcon = true;

export const IconCopyright = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconCopyright);
