// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconGear2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M4.10715 13.3125C4.20727 13.9191 4.11534 14.5536 3.75801 15.0539L2.37811 16.9857C1.80984 17.7813 1.90004 18.8711 2.59136 19.5624L4.43796 21.409C5.12929 22.1003 6.21908 22.1905 7.01465 21.6223L8.94688 20.2421C9.44709 19.8848 10.0815 19.7929 10.688 19.8929C11.1149 19.9634 11.5532 20 12 20C12.4469 20 12.8852 19.9633 13.3121 19.8929C13.9186 19.7928 14.5531 19.8848 15.0533 20.2421L16.9853 21.6221C17.7808 22.1903 18.8706 22.1001 19.562 21.4088L21.4086 19.5622C22.0999 18.8709 22.1901 17.7811 21.6218 16.9855L20.242 15.0538C19.8847 14.5535 19.7928 13.919 19.8929 13.3125C19.9633 12.8854 20 12.447 20 12C20 11.5531 19.9634 11.1148 19.8929 10.6879C19.7929 10.0814 19.8848 9.44692 20.2421 8.94671L21.6218 7.01515C22.19 6.21958 22.0999 5.12978 21.4085 4.43846L19.5619 2.59185C18.8706 1.90053 17.7808 1.81034 16.9852 2.3786L15.054 3.75803C14.5538 4.11536 13.9192 4.20729 13.3127 4.10716C12.8856 4.03666 12.4471 3.99999 12 3.99999C11.553 3.99999 11.1145 4.03665 10.6875 4.10714C10.0809 4.20725 9.44641 4.11532 8.94615 3.75799L7.0147 2.37838C6.21913 1.81012 5.12933 1.90031 4.43801 2.59163L2.5914 4.43824C1.90008 5.12956 1.80989 6.21936 2.37815 7.01493L3.75792 8.94661C4.11523 9.44684 4.20717 10.0813 4.10709 10.6878C4.03665 11.1148 4 11.5531 4 12C4 12.447 4.03667 12.8855 4.10715 13.3125Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
      <path
        d="M15 12.0001C15 13.6569 13.6569 15.0001 12 15.0001C10.3432 15.0001 9.00003 13.6569 9.00003 12.0001C9.00003 10.3432 10.3432 9.00006 12 9.00006C13.6569 9.00006 15 10.3432 15 12.0001Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconGear2.isIcon = true;

export const IconGear2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconGear2);
