// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconHeartSlash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 2L4.3116 4.3116M21 21L17.5064 17.5064M17.5064 17.5064C15.093 19.7034 12.5092 21 12 21C11 21 2 16 2 8.99999C2 7.03227 2.94824 5.38062 4.3116 4.3116M17.5064 17.5064L4.3116 4.3116M19.7977 15C19.8662 14.9076 19.9337 14.8144 20 14.7203C21.1765 13.0519 22 11.1174 22 8.99999C22 5.50001 19 3.04341 16 3.00001C14.5 2.9783 13 3.50003 12 5.00002C11 3.50003 9.47405 3.00001 8 3.00001C7.83316 3.00001 7.66632 3.00774 7.5 3.02294"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconHeartSlash.isIcon = true;

export const IconHeartSlash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconHeartSlash);
