// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconHome4(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2.5 9.5L3.97103 16.8552C4.33756 18.6879 4.52083 19.6042 4.99929 20.2896C5.42121 20.894 6.00194 21.3701 6.67737 21.6653C7.44332 22.0001 8.3778 22.0001 10.2467 22.0001H13.7533C15.6222 22.0001 16.5567 22.0001 17.3226 21.6653C17.9981 21.3701 18.5788 20.894 19.0007 20.2896C19.4792 19.6042 19.6624 18.6879 20.029 16.8552L21.5 9.5M1 11L7.47452 4.52548C9.05858 2.94142 9.85062 2.14938 10.7639 1.85263C11.5673 1.5916 12.4327 1.5916 13.2361 1.85263C14.1494 2.14938 14.9414 2.94142 16.5255 4.52548L23 11M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12C9 10.3431 10.3431 9 12 9C13.6569 9 15 10.3431 15 12Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconHome4.isIcon = true;

export const IconHome4 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconHome4);
