// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconShoppingBasket(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M6 7L9 2M15 2L18 7M9.24675 22H14.7533C16.6222 22 17.5567 22 18.3226 21.6653C18.9981 21.3701 19.5788 20.894 20.0007 20.2896C20.4792 19.6041 20.6624 18.6878 21.029 16.8551L21.469 14.6551C21.9938 12.0311 22.2562 10.7191 21.901 9.69225C21.5894 8.79163 20.9665 8.03184 20.1445 7.5497C19.2073 7 17.8693 7 15.1933 7H8.80675C6.13072 7 4.7927 7 3.8555 7.5497C3.03348 8.03184 2.4106 8.79163 2.09903 9.69225C1.74381 10.7191 2.00622 12.0311 2.53103 14.6551L2.97103 16.8551C3.33756 18.6878 3.52083 19.6041 3.99929 20.2896C4.4212 20.894 5.00194 21.3701 5.67737 21.6653C6.44332 22 7.37779 22 9.24675 22Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconShoppingBasket.isIcon = true;

export const IconShoppingBasket = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconShoppingBasket);
