// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconTag(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M11.9999 12.0001C11.9999 13.1047 11.1044 14.0001 9.99988 14.0001C8.89531 14.0001 7.99988 13.1047 7.99988 12.0001C7.99988 10.8956 8.89531 10.0001 9.99988 10.0001C11.1044 10.0001 11.9999 10.8956 11.9999 12.0001Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconTag.isIcon = true;

export const IconTag = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  _IconTag,
);
