// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconUmbrella(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 2C7.0253 2 4.49481 5.66632 3.22639 8.94588C2.75972 10.1525 2.52639 10.7558 2.71623 11.6339C2.85731 12.2865 3.44175 13.1392 3.99952 13.5062C4.75006 14 5.57225 14 7.21664 14H16.7834C18.4277 14 19.2499 14 20.0005 13.5062C20.5582 13.1392 21.1427 12.2865 21.2838 11.6339C21.4736 10.7558 21.2403 10.1525 20.7736 8.94588C19.5052 5.66632 16.9747 2 12 2ZM12 2C9.5 2 7.99992 8.5 8 14H16C16 8 14.5 2 12 2ZM12 14V20C12 21.1046 11.1046 22 10 22V22C8.89543 22 8 21.1046 8 20V19"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconUmbrella.isIcon = true;

export const IconUmbrella = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconUmbrella);
