// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * as wallet from "./wallet";
export * as line from "./line";
export * as filled from "./filled";
export * as gestalt from "./gestalt";
export * as duotone from "./duotone";
export * as duocolor from "./duocolor";
