// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconBraveWallet(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <g clipPath="url(#a)">
        <path
          d="m21.4 5.8.6-1.4-1.6-1.7c-.9-.8-2.7-.3-2.7-.3L15.6 0H8.2l-2 2.4s-2-.5-2.8.3L1.8 4.4l.6 1.4-.7 2 2.3 9c.5 1.9.9 2.6 2.2 3.6l4.3 3 1.4.6q.8-.1 1.4-.7l4.3-3c1.4-.9 1.7-1.6 2.2-3.5l2.3-9z"
          fill="url(#b)"
          fillRule="evenodd"
        />
        <path
          d="M17.1 3.9s2.7 3.3 2.7 4q0 .8-.7 1.2l-2 2.1c-.2.2-.6.6-.4 1.1q.6 1 .2 2-.7 1.1-1.4 1.1c-.5 0-1.4-.6-1.8-.8s-1.5-1.2-1.5-1.6 1.2-1 1.4-1.2 1.2-.7 1.2-1l-.3-.8c-.2-.5-.8-1.3-.7-1.8s1-.7 1.6-1l2-.7-.4-.2c-.5 0-1.7-.2-2.3 0l-1.6.5q-.2.2-.1.6l.5 3c0 .3.2.6-.3.7l-1.3.2-1.3-.2q-.5-.2-.3-.7l.5-3v-.6L9 6.3c-.5-.2-1.8 0-2.3 0q-.5 0-.3.2l2 .8c.6.2 1.4.4 1.5 1 .1.4-.4 1.2-.7 1.7L9 11c0 .2 1 .8 1.2 1 .3 0 1.4.7 1.4 1.1s-1.1 1.3-1.5 1.6l-1.7.8q-.8 0-1.5-1.1c-.4-.7 0-1.4.2-2q.1-.8-.4-1L4.7 9q-.6-.4-.7-1.3c0-.6 2.7-4 2.7-4l2.6.5 1.6-.4 1-.2 1 .2 1.6.4zm-2 12.5-.1.4c-.2 0-2.2 1.7-2.4 1.8l-.7.5q-.4-.1-.7-.5l-2.4-1.8q-.2-.2 0-.4l1.4-.8 1.7-.7 1.8.7z"
          fill="#fff"
          fillRule="evenodd"
        />
        <mask
          height="5"
          id="c"
          style={{ maskType: "alpha" }}
          width="18"
          x="3"
          y="0"
          maskUnits="userSpaceOnUse"
        >
          <path
            d="M17.7 2.4 15.6 0H8.2l-2 2.4s-2-.5-2.8.3c0 0 2.5-.2 3.3 1.2l2.6.4 1.6-.4 1-.2 1 .2 1.6.4 2.6-.4c.8-1.4 3.3-1.2 3.3-1.2-.9-.8-2.7-.3-2.7-.3"
            fill="#fff"
          />
        </mask>
        <g mask="url(#c)">
          <path
            d="M17.7 2.4 15.6 0H8.2l-2 2.4s-2-.5-2.8.3c0 0 2.5-.2 3.3 1.2l2.6.4 1.6-.4 1-.2 1 .2 1.6.4 2.6-.4c.8-1.4 3.3-1.2 3.3-1.2-.9-.8-2.7-.3-2.7-.3"
            fill="url(#d)"
          />
        </g>
      </g>
      <defs>
        <linearGradient
          id="b"
          gradientUnits="userSpaceOnUse"
          x1="1.7"
          x2="22.1"
          y1="12.2"
          y2="12.2"
        >
          <stop stopColor="#F50" />
          <stop offset=".4" stopColor="#F50" />
          <stop offset=".6" stopColor="#FF2000" />
          <stop offset="1" stopColor="#FF2000" />
        </linearGradient>
        <linearGradient
          id="d"
          gradientUnits="userSpaceOnUse"
          x1="3.8"
          x2="20.4"
          y1="2.2"
          y2="2.2"
        >
          <stop stopColor="#FF452A" />
          <stop offset="1" stopColor="#FF2000" />
        </linearGradient>
        <clipPath id="a">
          <path d="M0 0h24v24H0z" fill="#fff" />
        </clipPath>
      </defs>
    </svg>
  );
}

_IconBraveWallet.isIcon = true;

export const IconBraveWallet = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconBraveWallet);
