// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconCoinbaseCirc(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <g clipPath="url(#a)">
        <path d="M12 24a12 12 0 1 0 0-24 12 12 0 0 0 0 24" fill="#0052FF" />
        <path
          d="M3.6 12a8.4 8.4 0 1 0 16.8 0 8.4 8.4 0 0 0-16.8 0m6.2-2.7q-.5 0-.5.5v4.4q0 .5.5.5h4.4q.5 0 .5-.5V9.8q0-.5-.5-.5z"
          fill="#fff"
          fillRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="a">
          <path d="M0 0h24v24H0z" fill="#fff" />
        </clipPath>
      </defs>
    </svg>
  );
}

_IconCoinbaseCirc.isIcon = true;

export const IconCoinbaseCirc = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconCoinbaseCirc);
