// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./wallet-connect.tsx";
export * from "./wallet-connect-rect.tsx";
export * from "./wallet-connect-circ.tsx";
export * from "./trust-wallet.tsx";
export * from "./trust-wallet-rect.tsx";
export * from "./trust-wallet-circ.tsx";
export * from "./rainbow.tsx";
export * from "./rainbow-rect.tsx";
export * from "./rainbow-circ.tsx";
export * from "./rabby.tsx";
export * from "./rabby-circ.tsx";
export * from "./okx-wallet.tsx";
export * from "./metamask.tsx";
export * from "./metamask-rect.tsx";
export * from "./metamask-circ.tsx";
export * from "./leap.tsx";
export * from "./keplr.tsx";
export * from "./keplr-rect.tsx";
export * from "./keplr-circ.tsx";
export * from "./coinbase.tsx";
export * from "./coinbase-rect.tsx";
export * from "./coinbase-circ.tsx";
export * from "./brave-wallet.tsx";
export * from "./brave-wallet-rect.tsx";
export * from "./brave-wallet-circ.tsx";
