// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./wallet-connect.tsx";
export * from "./wallet-connect-rect.tsx";
export * from "./wallet-connect-circ.tsx";
export * from "./metamask.tsx";
export * from "./metamask-rect.tsx";
export * from "./metamask-circ.tsx";
export * from "./keplr.tsx";
export * from "./keplr-rect.tsx";
export * from "./keplr-circ.tsx";
