// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./wallet-connect";
export * from "./wallet-connect-rect";
export * from "./wallet-connect-circ";
export * from "./metamask";
export * from "./metamask-rect";
export * from "./metamask-circ";
export * from "./keplr";
export * from "./keplr-rect";
export * from "./keplr-circ";
