// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconOkxWallet(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <rect height="8" width="8" fill="white" rx="1" />
      <rect height="8" width="8" fill="white" rx="1" x="8" y="8" />
      <rect height="8" width="8" fill="white" rx="1" x="16" />
      <rect height="8" width="8" fill="white" rx="1" x="16" y="16" />
      <rect height="8" width="8" fill="white" rx="1" y="16" />
    </svg>
  );
}

_IconOkxWallet.isIcon = true;

export const IconOkxWallet = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconOkxWallet);
