// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconRainbowRect(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M0 10.9C0 7 0 5.2.7 3.7a7 7 0 0 1 3-3C5.2 0 7.1 0 11 0h2c3.8 0 5.7 0 7.2.7q2 1 3 3c.7 1.5.7 3.4.7 7.2V13c0 3.8 0 5.7-.7 7.2a7 7 0 0 1-3 3c-1.5.7-3.4.7-7.2.7h-2c-3.8 0-5.7 0-7.2-.7a7 7 0 0 1-3-3C0 18.8 0 16.9 0 13z"
        fill="url(#a)"
      />
      <path
        d="M4 7.6h1.2c6.2 0 11.2 5 11.2 11.2V20h2.4q1.1 0 1.2-1.2C20 10.6 13.4 4 5.2 4Q4.1 4 4 5.2z"
        fill="url(#b)"
      />
      <path d="M16.8 18.8H20q0 1.1-1.2 1.2h-2z" fill="url(#c)" />
      <path d="M5.2 4v3.2H4v-2Q4 4.1 5.2 4" fill="url(#d)" />
      <path
        d="M4 7.2h1.2c6.4 0 11.6 5.2 11.6 11.6V20h-3.6v-1.2a8 8 0 0 0-8-8H4z"
        fill="url(#e)"
      />
      <path d="M13.6 18.8h3.2V20h-3.2z" fill="url(#f)" />
      <path d="M4 10.4V7.2h1.2v3.2z" fill="url(#g)" />
      <path
        d="M4 12.4q0 1.1 1.2 1.2c2.9 0 5.2 2.3 5.2 5.2q0 1.1 1.2 1.2h2v-1.2c0-4.6-3.8-8.4-8.4-8.4H4z"
        fill="url(#h)"
      />
      <path d="M10.4 18.8h3.2V20h-2q-1.1 0-1.2-1.2" fill="url(#i)" />
      <path d="M5.2 13.6q-1.1 0-1.2-1.2v-2h1.2z" fill="url(#j)" />
      <defs>
        <radialGradient
          id="b"
          cx="0"
          cy="0"
          gradientTransform="rotate(-90 12 6.8)scale(14.8)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop offset=".8" stopColor="#FF4000" />
          <stop offset="1" stopColor="#8754C9" />
        </radialGradient>
        <radialGradient
          id="e"
          cx="0"
          cy="0"
          gradientTransform="rotate(-90 12 6.8)scale(11.6)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop offset=".7" stopColor="#FFF700" />
          <stop offset="1" stopColor="#FF9901" />
        </radialGradient>
        <radialGradient
          id="h"
          cx="0"
          cy="0"
          gradientTransform="rotate(-90 12 6.8)scale(8.4)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop offset=".6" stopColor="#0AF" />
          <stop offset="1" stopColor="#01DA40" />
        </radialGradient>
        <radialGradient
          id="i"
          cx="0"
          cy="0"
          gradientTransform="matrix(3.4 0 0 9.06667 10.2 19.4)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop stopColor="#0AF" />
          <stop offset="1" stopColor="#01DA40" />
        </radialGradient>
        <radialGradient
          id="j"
          cx="0"
          cy="0"
          gradientTransform="matrix(0 -3.4 64.4741 0 0 13.6)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop stopColor="#0AF" />
          <stop offset="1" stopColor="#01DA40" />
        </radialGradient>
        <linearGradient
          id="a"
          gradientUnits="userSpaceOnUse"
          x1="12"
          x2="12"
          y1="0"
          y2="24"
        >
          <stop stopColor="#174299" />
          <stop offset="1" stopColor="#001E59" />
        </linearGradient>
        <linearGradient
          id="c"
          gradientUnits="userSpaceOnUse"
          x1="16.6"
          x2="20"
          y1="19.4"
          y2="19.4"
        >
          <stop stopColor="#FF4000" />
          <stop offset="1" stopColor="#8754C9" />
        </linearGradient>
        <linearGradient
          id="d"
          gradientUnits="userSpaceOnUse"
          x1="4.6"
          x2="4.6"
          y1="4"
          y2="7.4"
        >
          <stop stopColor="#8754C9" />
          <stop offset="1" stopColor="#FF4000" />
        </linearGradient>
        <linearGradient
          id="f"
          gradientUnits="userSpaceOnUse"
          x1="13.6"
          x2="16.8"
          y1="19.4"
          y2="19.4"
        >
          <stop stopColor="#FFF700" />
          <stop offset="1" stopColor="#FF9901" />
        </linearGradient>
        <linearGradient
          id="g"
          gradientUnits="userSpaceOnUse"
          x1="4.6"
          x2="4.6"
          y1="10.4"
          y2="7.2"
        >
          <stop stopColor="#FFF700" />
          <stop offset="1" stopColor="#FF9901" />
        </linearGradient>
      </defs>
    </svg>
  );
}

_IconRainbowRect.isIcon = true;

export const IconRainbowRect = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconRainbowRect);
