// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconRainbowCirc(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <g clipPath="url(#a)">
        <mask
          height="24"
          id="b"
          style={{ maskType: "alpha" }}
          width="24"
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
        >
          <circle cx="12" cy="12" fill="#D9D9D9" r="12" />
        </mask>
        <g mask="url(#b)">
          <path d="M0 0h24v24H0z" fill="url(#c)" />
        </g>
        <path
          d="M5.3 8.3h1c5.2 0 9.4 4.2 9.4 9.4v1h2q.9-.1 1-1c0-6.8-5.6-12.4-12.4-12.4a1 1 0 0 0-1 1z"
          fill="url(#d)"
        />
        <path d="M16 17.7h2.7q-.1.9-1 1H16z" fill="url(#e)" />
        <path d="M6.3 5.3V8h-1V6.3q.1-.9 1-1" fill="url(#f)" />
        <path
          d="M5.3 8h1c5.4 0 9.7 4.3 9.7 9.7v1h-3v-1C13 14 10 11 6.3 11h-1z"
          fill="url(#g)"
        />
        <path d="M13.3 17.7H16v1h-2.7z" fill="url(#h)" />
        <path d="M5.3 10.7V8h1v2.7z" fill="url(#i)" />
        <path
          d="M5.3 12.3q.1 1 1 1c2.4 0 4.4 2 4.4 4.4q0 .9 1 1h1.6v-1a7 7 0 0 0-7-7h-1z"
          fill="url(#j)"
        />
        <path d="M10.7 17.7h2.6v1h-1.6a1 1 0 0 1-1-1" fill="url(#k)" />
        <path d="M6.3 13.3a1 1 0 0 1-1-1v-1.6h1z" fill="url(#l)" />
      </g>
      <defs>
        <radialGradient
          id="d"
          cx="0"
          cy="0"
          gradientTransform="rotate(-90 12 5.7)scale(12.3333)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop offset=".8" stopColor="#FF4000" />
          <stop offset="1" stopColor="#8754C9" />
        </radialGradient>
        <radialGradient
          id="g"
          cx="0"
          cy="0"
          gradientTransform="rotate(-90 12 5.7)scale(9.66667)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop offset=".7" stopColor="#FFF700" />
          <stop offset="1" stopColor="#FF9901" />
        </radialGradient>
        <radialGradient
          id="j"
          cx="0"
          cy="0"
          gradientTransform="matrix(0 -7 7 0 6.3 17.7)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop offset=".6" stopColor="#0AF" />
          <stop offset="1" stopColor="#01DA40" />
        </radialGradient>
        <radialGradient
          id="k"
          cx="0"
          cy="0"
          gradientTransform="matrix(2.83333 0 0 7.55556 10.5 18.2)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop stopColor="#0AF" />
          <stop offset="1" stopColor="#01DA40" />
        </radialGradient>
        <radialGradient
          id="l"
          cx="0"
          cy="0"
          gradientTransform="matrix(0 -2.83333 53.7284 0 5.8 13.5)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop stopColor="#0AF" />
          <stop offset="1" stopColor="#01DA40" />
        </radialGradient>
        <linearGradient
          id="c"
          gradientUnits="userSpaceOnUse"
          x1="12"
          x2="12"
          y1="0"
          y2="24"
        >
          <stop stopColor="#174299" />
          <stop offset="1" stopColor="#001E59" />
        </linearGradient>
        <linearGradient
          id="e"
          gradientUnits="userSpaceOnUse"
          x1="15.8"
          x2="18.7"
          y1="18.2"
          y2="18.2"
        >
          <stop stopColor="#FF4000" />
          <stop offset="1" stopColor="#8754C9" />
        </linearGradient>
        <linearGradient
          id="f"
          gradientUnits="userSpaceOnUse"
          x1="5.8"
          x2="5.8"
          y1="5.3"
          y2="8.2"
        >
          <stop stopColor="#8754C9" />
          <stop offset="1" stopColor="#FF4000" />
        </linearGradient>
        <linearGradient
          id="h"
          gradientUnits="userSpaceOnUse"
          x1="13.3"
          x2="16"
          y1="18.2"
          y2="18.2"
        >
          <stop stopColor="#FFF700" />
          <stop offset="1" stopColor="#FF9901" />
        </linearGradient>
        <linearGradient
          id="i"
          gradientUnits="userSpaceOnUse"
          x1="5.8"
          x2="5.8"
          y1="10.7"
          y2="8"
        >
          <stop stopColor="#FFF700" />
          <stop offset="1" stopColor="#FF9901" />
        </linearGradient>
        <clipPath id="a">
          <path d="M0 0h24v24H0z" fill="#fff" />
        </clipPath>
      </defs>
    </svg>
  );
}

_IconRainbowCirc.isIcon = true;

export const IconRainbowCirc = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconRainbowCirc);
