// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconWalletConnectCirc(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <g clipPath="url(#clip0_1_378)">
        <path
          d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z"
          fill="url(#paint0_radial_1_378)"
        />
        <path
          d="M7.53516 9.26836C9.94922 6.91055 13.868 6.91055 16.282 9.26836L16.5727 9.5543C16.6945 9.67148 16.6945 9.86367 16.5727 9.98086L15.5789 10.9512C15.518 11.0121 15.4195 11.0121 15.3586 10.9512L14.9602 10.5621C13.2727 8.9168 10.5445 8.9168 8.85703 10.5621L8.43047 10.9793C8.36953 11.0402 8.27109 11.0402 8.21016 10.9793L7.21641 10.009C7.09453 9.8918 7.09453 9.69961 7.21641 9.58242L7.53516 9.26836ZM18.3398 11.2746L19.2258 12.1371C19.3477 12.2543 19.3477 12.4465 19.2258 12.5637L15.2367 16.459C15.1148 16.5762 14.918 16.5762 14.8008 16.459L11.9695 13.6934C11.9414 13.6652 11.8898 13.6652 11.8617 13.6934L9.03047 16.459C8.90859 16.5762 8.71172 16.5762 8.59453 16.459L4.59141 12.5637C4.46953 12.4465 4.46953 12.2543 4.59141 12.1371L5.47734 11.2746C5.59922 11.1574 5.79609 11.1574 5.91328 11.2746L8.74453 14.0402C8.77266 14.0684 8.82422 14.0684 8.85234 14.0402L11.6836 11.2746C11.8055 11.1574 12.0023 11.1574 12.1195 11.2746L14.9508 14.0402C14.9789 14.0684 15.0305 14.0684 15.0586 14.0402L17.8898 11.2746C18.0211 11.1574 18.218 11.1574 18.3398 11.2746Z"
          fill="white"
        />
      </g>
      <defs>
        <radialGradient
          id="paint0_radial_1_378"
          cx="0"
          cy="0"
          gradientTransform="translate(7.43866e-05 12.0004) scale(24)"
          gradientUnits="userSpaceOnUse"
          r="1"
        >
          <stop stopColor="#5D9DF6" />
          <stop offset="1" stopColor="#006FFF" />
        </radialGradient>
        <clipPath id="clip0_1_378">
          <rect height="24" width="24" fill="white" />
        </clipPath>
      </defs>
    </svg>
  );
}

_IconWalletConnectCirc.isIcon = true;

export const IconWalletConnectCirc = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconWalletConnectCirc);
