// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconWalletConnect(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M7.62659 9.26719C10.0407 6.90938 13.9594 6.90938 16.3735 9.26719L16.6641 9.55313C16.786 9.67031 16.786 9.8625 16.6641 9.97969L15.6703 10.95C15.6094 11.0109 15.511 11.0109 15.45 10.95L15.0516 10.5609C13.3641 8.91563 10.636 8.91563 8.94846 10.5609L8.5219 10.9781C8.46096 11.0391 8.36252 11.0391 8.30159 10.9781L7.30784 10.0078C7.18596 9.89063 7.18596 9.69844 7.30784 9.58125L7.62659 9.26719ZM18.4313 11.2734L19.3172 12.1359C19.4391 12.2531 19.4391 12.4453 19.3172 12.5625L15.3281 16.4578C15.2063 16.575 15.0094 16.575 14.8922 16.4578L12.061 13.6922C12.0328 13.6641 11.9813 13.6641 11.9531 13.6922L9.1219 16.4578C9.00002 16.575 8.80315 16.575 8.68596 16.4578L4.68284 12.5625C4.56096 12.4453 4.56096 12.2531 4.68284 12.1359L5.56877 11.2734C5.69065 11.1563 5.88753 11.1563 6.00471 11.2734L8.83596 14.0391C8.86409 14.0672 8.91565 14.0672 8.94377 14.0391L11.775 11.2734C11.8969 11.1563 12.0938 11.1563 12.211 11.2734L15.0422 14.0391C15.0703 14.0672 15.1219 14.0672 15.15 14.0391L17.9813 11.2734C18.1125 11.1563 18.3094 11.1563 18.4313 11.2734Z"
        fill="white"
      />
    </svg>
  );
}

_IconWalletConnect.isIcon = true;

export const IconWalletConnect = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconWalletConnect);
