// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconDistributeVertically(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3 22H21M3 2H21M8.8 17H15.2C16.8802 17 17.7202 17 18.362 16.673C18.9265 16.3854 19.3854 15.9265 19.673 15.362C20 14.7202 20 13.8802 20 12.2V11.8C20 10.1198 20 9.27976 19.673 8.63803C19.3854 8.07354 18.9265 7.6146 18.362 7.32698C17.7202 7 16.8802 7 15.2 7H8.8C7.11984 7 6.27976 7 5.63803 7.32698C5.07354 7.6146 4.6146 8.07354 4.32698 8.63803C4 9.27976 4 10.1198 4 11.8V12.2C4 13.8802 4 14.7202 4.32698 15.362C4.6146 15.9265 5.07354 16.3854 5.63803 16.673C6.27976 17 7.11984 17 8.8 17Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconDistributeVertically.isIcon = true;

export const IconDistributeVertically = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconDistributeVertically);
