// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSelection(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M10 2H12H14M18 2H18.3889V2C20.3832 2 22 3.61675 22 5.61111V5.61111V6M2 6V5.61111V5.61111C2 3.61675 3.61675 2 5.61111 2V2H6M2 10V12V14M2 18V18.3889V18.3889C2 20.3832 3.61675 22 5.61111 22V22H6M10 22H12H14M18 22H18.3889V22C20.3833 22 22 20.3833 22 18.3889V18.3889V18M22 14V12V10"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconSelection.isIcon = true;

export const IconSelection = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSelection);
