// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSliderHorizontal(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 4V20M22 4V20M10.8 21H13.2C14.8802 21 15.7202 21 16.362 20.673C16.9265 20.3854 17.3854 19.9265 17.673 19.362C18 18.7202 18 17.8802 18 16.2V7.8C18 6.11984 18 5.27976 17.673 4.63803C17.3854 4.07354 16.9265 3.6146 16.362 3.32698C15.7202 3 14.8802 3 13.2 3H10.8C9.11984 3 8.27976 3 7.63803 3.32698C7.07354 3.6146 6.6146 4.07354 6.32698 4.63803C6 5.27976 6 6.11984 6 7.8V16.2C6 17.8802 6 18.7202 6.32698 19.362C6.6146 19.9265 7.07354 20.3854 7.63803 20.673C8.27976 21 9.11984 21 10.8 21Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconSliderHorizontal.isIcon = true;

export const IconSliderHorizontal = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSliderHorizontal);
