// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconCutlery3(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M7 2V11M7 22V11M7 11L5.42496 9.94997C4.90398 9.60265 4.64349 9.42899 4.45491 9.19955C4.28796 8.99643 4.1627 8.76238 4.0863 8.5108C4 8.22663 4 7.91355 4 7.28741V2M7 11L8.57504 9.94997C9.09602 9.60265 9.35651 9.42899 9.54509 9.19955C9.71204 8.99643 9.8373 8.76238 9.9137 8.5108C10 8.22663 10 7.91355 10 7.28741V2M17 2V14M17 14C15.3431 14 13.5 15.7909 13.5 18C13.5 20.2091 15.3431 22 17 22C18.6569 22 20.5 20.2091 20.5 18C20.5 15.7909 18.6569 14 17 14Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconCutlery3.isIcon = true;

export const IconCutlery3 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconCutlery3);
