// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconCutlery2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 21L8 15L11 12M16 13L20.7373 8.26274C21.5293 7.47071 21.9253 7.07469 22.0737 6.61803C22.2042 6.21635 22.2042 5.78365 22.0737 5.38197C21.9253 4.92531 21.5293 4.52929 20.7373 3.73726L20 3L13 10M3.5 4.5L9.5 10.5M9.5 10.5L7.58392 10.7737C7.00315 10.8567 6.71277 10.8982 6.43537 10.8601C6.18968 10.8264 5.9524 10.7473 5.73563 10.6269C5.49088 10.4909 5.28346 10.2835 4.86863 9.86863L2 7M9.5 10.5L9.77373 8.58392C9.85669 8.00315 9.89818 7.71277 9.86013 7.43537C9.82644 7.18968 9.74734 6.9524 9.62689 6.73563C9.49088 6.49088 9.28346 6.28346 8.86863 5.86863L6 3M9.5 10.5L20 21"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconCutlery2.isIcon = true;

export const IconCutlery2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconCutlery2);
