// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./glass-wine.tsx";
export * from "./glass-cocktail.tsx";
export * from "./cutlery.tsx";
export * from "./cutlery-4.tsx";
export * from "./cutlery-3.tsx";
export * from "./cutlery-2.tsx";
export * from "./coffee.tsx";
