// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./route.tsx";
export * from "./pin.tsx";
export * from "./pin-slash.tsx";
export * from "./pin-plus.tsx";
export * from "./pin-minus.tsx";
export * from "./pin-cross.tsx";
export * from "./pin-check.tsx";
export * from "./pin-3.tsx";
export * from "./pin-2.tsx";
export * from "./map-view.tsx";
export * from "./gps.tsx";
export * from "./gps-slash.tsx";
export * from "./globe.tsx";
export * from "./globe-2.tsx";
export * from "./direction.tsx";
export * from "./direction-2.tsx";
export * from "./compass.tsx";
export * from "./360-degrees.tsx";
