// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconRoute(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M10.0303 1.96967C9.73744 1.67678 9.26256 1.67678 8.96967 1.96967C8.67678 2.26256 8.67678 2.73744 8.96967 3.03033L10.1893 4.25H6.5C4.15279 4.25 2.25 6.15279 2.25 8.5C2.25 10.8472 4.15279 12.75 6.5 12.75H16.5C18.0188 12.75 19.25 13.9812 19.25 15.5C19.25 17.0188 18.0188 18.25 16.5 18.25H8C7.96849 18.25 7.93744 18.2519 7.90695 18.2557C7.57591 16.9589 6.39994 16 5 16C3.34315 16 2 17.3431 2 19C2 20.6569 3.34315 22 5 22C6.39994 22 7.57591 21.0411 7.90695 19.7443C7.93744 19.7481 7.96849 19.75 8 19.75H16.5C18.8472 19.75 20.75 17.8472 20.75 15.5C20.75 13.1528 18.8472 11.25 16.5 11.25H6.5C4.98122 11.25 3.75 10.0188 3.75 8.5C3.75 6.98122 4.98122 5.75 6.5 5.75H10.1893L8.96967 6.96967C8.67678 7.26256 8.67678 7.73744 8.96967 8.03033C9.26256 8.32322 9.73744 8.32322 10.0303 8.03033L12.5303 5.53033C12.8232 5.23744 12.8232 4.76256 12.5303 4.46967L10.0303 1.96967ZM18 8C19.6569 8 21 6.65685 21 5C21 3.34315 19.6569 2 18 2C16.3431 2 15 3.34315 15 5C15 6.65685 16.3431 8 18 8Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconRoute.isIcon = true;

export const IconRoute = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconRoute);
