// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconAndroid(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M9 19H8.2C7.07989 19 6.51984 19 6.09202 18.782C5.71569 18.5903 5.40973 18.2843 5.21799 17.908C5 17.4802 5 16.9201 5 15.8V10M9 19V22M9 19H15M15 19H15.8C16.9201 19 17.4802 19 17.908 18.782C18.2843 18.5903 18.5903 18.2843 18.782 17.908C19 17.4802 19 16.9201 19 15.8V10M15 19V22M5 10H19M5 10C5 6.13401 8.13401 3 12 3C15.866 3 19 6.13401 19 10M2 10V16M22 10V16M5.5 1.5L8 4M17.5 1.5L15.5 3.5M10 7C10 7.27614 9.77614 7.5 9.5 7.5C9.22386 7.5 9 7.27614 9 7M10 7C10 6.72386 9.77614 6.5 9.5 6.5C9.22386 6.5 9 6.72386 9 7M10 7H9M15 7C15 7.27614 14.7761 7.5 14.5 7.5C14.2239 7.5 14 7.27614 14 7M15 7C15 6.72386 14.7761 6.5 14.5 6.5C14.2239 6.5 14 6.72386 14 7M15 7H14"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconAndroid.isIcon = true;

export const IconAndroid = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconAndroid);
