// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconDribbble(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M8.74405 2.55447C12.6297 8.19001 15.2331 14.44 16.5454 20.9044M21.9755 12.8911C15.4276 11.4589 8.84406 14.0189 4.92951 19.0711M4.92951 19.0711C8.83483 22.9763 15.1656 22.9763 19.071 19.071C22.9763 15.1658 22.9763 8.83414 19.071 4.92891M4.92951 19.0711C1.02416 15.1659 1.02316 8.83417 4.92851 4.92895C8.83386 1.02371 15.1657 1.02367 19.071 4.92891M2.06166 10.9289C8.12848 11.5722 14.4209 9.57779 19.071 4.92891"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconDribbble.isIcon = true;

export const IconDribbble = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconDribbble);
