// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSketch(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 21L3.20809 10.9521C2.59911 10.2561 2.29462 9.90813 2.16812 9.51342C2.05656 9.16531 2.04254 8.79328 2.12759 8.43775C2.22402 8.03464 2.50146 7.66472 3.05633 6.92489L5.04 4.28C5.392 3.81067 5.568 3.576 5.79105 3.40675C5.9886 3.25685 6.21232 3.14499 6.45077 3.07689C6.72 3 7.01334 3 7.6 3H12M12 21L20.7919 10.9521C21.4009 10.2561 21.7054 9.90813 21.8319 9.51342C21.9434 9.16531 21.9575 8.79328 21.8724 8.43775C21.776 8.03464 21.4985 7.66472 20.9437 6.92489L18.96 4.28C18.608 3.81067 18.432 3.576 18.2089 3.40675C18.0114 3.25685 17.7877 3.14499 17.5492 3.07689C17.28 3 16.9867 3 16.4 3H12M12 21L8 9M12 21L16 9M12 3L8 9M12 3L16 9M8 9H16M8 9H2.5M16 9H21.5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconSketch.isIcon = true;

export const IconSketch = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSketch);
