// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconNote2Text(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M8.75 1C8.75 0.585786 8.41421 0.25 8 0.25C7.58579 0.25 7.25 0.585786 7.25 1V2.25001V2.25001C3.93629 2.25001 1.25 4.9363 1.25 8.25001V13.15C1.25 16.5103 1.25 18.1905 1.90396 19.474C2.4792 20.6029 3.39708 21.5208 4.52606 22.0961C5.80953 22.75 7.48968 22.75 10.85 22.75H13.15C16.5103 22.75 18.1905 22.75 19.4739 22.0961C20.6029 21.5208 21.5208 20.6029 22.096 19.474C22.75 18.1905 22.75 16.5103 22.75 13.15V8.25001C22.75 4.9363 20.0637 2.25001 16.75 2.25001V2.25001V1C16.75 0.585786 16.4142 0.25 16 0.25C15.5858 0.25 15.25 0.585786 15.25 1V2.25001H12.75V1C12.75 0.585786 12.4142 0.25 12 0.25C11.5858 0.25 11.25 0.585786 11.25 1V2.25001H8.75V1ZM6.25 9.00002C6.25 8.58581 6.58579 8.25002 7 8.25002H17C17.4142 8.25002 17.75 8.58581 17.75 9.00002C17.75 9.41424 17.4142 9.75002 17 9.75002H7C6.58579 9.75002 6.25 9.41424 6.25 9.00002ZM6.25 13C6.25 12.5858 6.58579 12.25 7 12.25H13C13.4142 12.25 13.75 12.5858 13.75 13C13.75 13.4142 13.4142 13.75 13 13.75H7C6.58579 13.75 6.25 13.4142 6.25 13ZM6.25 17C6.25 16.5858 6.58579 16.25 7 16.25H9C9.41421 16.25 9.75 16.5858 9.75 17C9.75 17.4142 9.41421 17.75 9 17.75H7C6.58579 17.75 6.25 17.4142 6.25 17Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconNote2Text.isIcon = true;

export const IconNote2Text = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconNote2Text);
