// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconChevronRight(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M14.8686 10.8687C15.2646 11.2647 15.4627 11.4627 15.5368 11.691C15.6021 11.8919 15.6021 12.1082 15.5368 12.3091C15.4627 12.5374 15.2646 12.7354 14.8686 13.1314L11.7314 16.2687C10.8746 17.1254 10.4462 17.5538 10.0785 17.5828C9.75934 17.6079 9.44749 17.4787 9.23959 17.2353C9 16.9548 9 16.349 9 15.1373L9 8.8628C9 7.65117 9 7.04536 9.23959 6.76483C9.44749 6.52142 9.75934 6.39224 10.0785 6.41736C10.4462 6.4463 10.8746 6.87468 11.7314 7.73143L14.8686 10.8687Z"
        fill="currentColor"
      />
    </svg>
  );
}

_IconChevronRight.isIcon = true;

export const IconChevronRight = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconChevronRight);
