// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconChevronRightRec(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.98005 1.79497C5.04961 1.25 6.44974 1.25 9.25 1.25H14.75C17.5503 1.25 18.9504 1.25 20.02 1.79497C20.9608 2.27433 21.7257 3.03924 22.205 3.98005C22.75 5.04961 22.75 6.44974 22.75 9.25V14.75C22.75 17.5503 22.75 18.9504 22.205 20.02C21.7257 20.9608 20.9608 21.7257 20.02 22.205C18.9504 22.75 17.5503 22.75 14.75 22.75H9.25C6.44974 22.75 5.04961 22.75 3.98005 22.205C3.03924 21.7257 2.27433 20.9608 1.79497 20.02C1.25 18.9504 1.25 17.5503 1.25 14.75V9.25C1.25 6.44974 1.25 5.04961 1.79497 3.98005C2.27433 3.03924 3.03924 2.27433 3.98005 1.79497ZM15.3053 11.5365C15.194 11.194 14.897 10.897 14.3029 10.303L13.0971 9.09708C11.8119 7.81195 11.1694 7.16939 10.6177 7.12597C10.139 7.0883 9.67123 7.28206 9.35939 7.64717C9 8.06797 9 8.97669 9 10.7941V13.2059C9 15.0234 9 15.9321 9.35939 16.3529C9.67123 16.718 10.139 16.9118 10.6177 16.8741C11.1694 16.8307 11.8119 16.1881 13.0971 14.903L14.3029 13.6971L14.303 13.6971C14.897 13.1031 15.194 12.806 15.3053 12.4636C15.4032 12.1623 15.4032 11.8378 15.3053 11.5365Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconChevronRightRec.isIcon = true;

export const IconChevronRightRec = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconChevronRightRec);
