// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconLogIn2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M9.43404 1.68594C10.2897 1.24997 11.4098 1.24997 13.65 1.24997H16.35C18.5902 1.24997 19.7103 1.24997 20.566 1.68594C21.3186 2.06944 21.9305 2.68136 22.314 3.43401C22.75 4.28965 22.75 5.40976 22.75 7.64997V16.35C22.75 18.5902 22.75 19.7103 22.314 20.5659C21.9305 21.3186 21.3186 21.9305 20.566 22.314C19.7103 22.75 18.5902 22.75 16.35 22.75H13.65C11.4098 22.75 10.2897 22.75 9.43404 22.314C8.68139 21.9305 8.06947 21.3186 7.68597 20.5659C7.25 19.7103 7.25 18.5902 7.25 16.35V12.7501L15.1893 12.7501L12.4697 15.4697C12.1768 15.7626 12.1768 16.2375 12.4697 16.5304C12.7626 16.8233 13.2374 16.8233 13.5303 16.5304L17.5303 12.5304C17.8232 12.2375 17.8232 11.7626 17.5303 11.4697L13.5303 7.46972C13.2374 7.17683 12.7626 7.17683 12.4697 7.46972C12.1768 7.76261 12.1768 8.23749 12.4697 8.53038L15.1893 11.2501L7.25 11.2501V7.64997C7.25 5.40976 7.25 4.28965 7.68597 3.43401C8.06947 2.68136 8.68139 2.06944 9.43404 1.68594ZM7.25 11.2501H2C1.58579 11.2501 1.25 11.5858 1.25 12.0001C1.25 12.4143 1.58579 12.7501 2 12.7501H7.25V11.2501Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconLogIn2.isIcon = true;

export const IconLogIn2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconLogIn2);
