// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconLogIn3(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M7.25 9C7.25 4.71979 10.7198 1.25 15 1.25C19.2802 1.25 22.75 4.71979 22.75 9V15C22.75 19.2802 19.2802 22.75 15 22.75C10.7198 22.75 7.25 19.2802 7.25 15V12.75L15.1893 12.75L12.4697 15.4697C12.1768 15.7626 12.1768 16.2375 12.4697 16.5304C12.7626 16.8233 13.2374 16.8233 13.5303 16.5304L17.5303 12.5304C17.8232 12.2375 17.8232 11.7626 17.5303 11.4697L13.5303 7.46971C13.2374 7.17682 12.7626 7.17682 12.4697 7.46971C12.1768 7.7626 12.1768 8.23748 12.4697 8.53037L15.1893 11.25L7.25 11.25V9ZM7.25 11.25H2C1.58579 11.25 1.25 11.5858 1.25 12C1.25 12.4143 1.58579 12.75 2 12.75H7.25V11.25Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconLogIn3.isIcon = true;

export const IconLogIn3 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconLogIn3);
