// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconRedoRec(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.98005 1.79497C5.04961 1.25 6.44974 1.25 9.25 1.25H14.75C17.5503 1.25 18.9504 1.25 20.02 1.79497C20.9608 2.27433 21.7257 3.03924 22.205 3.98005C22.75 5.04961 22.75 6.44974 22.75 9.25V14.75C22.75 17.5503 22.75 18.9504 22.205 20.02C21.7257 20.9608 20.9608 21.7257 20.02 22.205C18.9504 22.75 17.5503 22.75 14.75 22.75H9.25C6.44974 22.75 5.04961 22.75 3.98005 22.205C3.03924 21.7257 2.27433 20.9608 1.79497 20.02C1.25 18.9504 1.25 17.5503 1.25 14.75V9.25C1.25 6.44974 1.25 5.04961 1.79497 3.98005C2.27433 3.03924 3.03924 2.27433 3.98005 1.79497ZM16.5303 5.46967C16.2374 5.17678 15.7626 5.17678 15.4697 5.46967C15.1768 5.76257 15.1768 6.23744 15.4697 6.53033L16.1893 7.24999H10.5C7.60052 7.24999 5.25 9.6005 5.25 12.5C5.25 15.3995 7.60052 17.75 10.5 17.75H13C13.4142 17.75 13.75 17.4142 13.75 17C13.75 16.5858 13.4142 16.25 13 16.25H10.5C8.42894 16.25 6.75 14.5711 6.75 12.5C6.75 10.4289 8.42894 8.74999 10.5 8.74999H16.1893L15.4697 9.46966C15.1768 9.76255 15.1768 10.2374 15.4697 10.5303C15.7626 10.8232 16.2374 10.8232 16.5303 10.5303L18.5303 8.53032C18.671 8.38966 18.75 8.1989 18.75 7.99999C18.75 7.80107 18.671 7.61031 18.5303 7.46966L16.5303 5.46967Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconRedoRec.isIcon = true;

export const IconRedoRec = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconRedoRec);
