// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconUndoRec(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.98005 1.79497C5.04961 1.25 6.44974 1.25 9.25 1.25H14.75C17.5503 1.25 18.9504 1.25 20.02 1.79497C20.9608 2.27433 21.7257 3.03924 22.205 3.98005C22.75 5.04961 22.75 6.44974 22.75 9.25V14.75C22.75 17.5503 22.75 18.9504 22.205 20.02C21.7257 20.9608 20.9608 21.7257 20.02 22.205C18.9504 22.75 17.5503 22.75 14.75 22.75H9.25C6.44974 22.75 5.04961 22.75 3.98005 22.205C3.03924 21.7257 2.27433 20.9608 1.79497 20.02C1.25 18.9504 1.25 17.5503 1.25 14.75V9.25C1.25 6.44974 1.25 5.04961 1.79497 3.98005C2.27433 3.03924 3.03924 2.27433 3.98005 1.79497ZM8.53033 6.53033C8.82322 6.23744 8.82322 5.76257 8.53033 5.46967C8.23744 5.17678 7.76257 5.17678 7.46967 5.46967L5.46967 7.46966C5.32902 7.61031 5.25 7.80107 5.25 7.99999C5.25 8.1989 5.32902 8.38966 5.46967 8.53032L7.46967 10.5303C7.76256 10.8232 8.23744 10.8232 8.53033 10.5303C8.82322 10.2374 8.82322 9.76255 8.53033 9.46966L7.81066 8.74999H13.5C15.5711 8.74999 17.25 10.4289 17.25 12.5C17.25 14.5711 15.5711 16.25 13.5 16.25H11C10.5858 16.25 10.25 16.5858 10.25 17C10.25 17.4142 10.5858 17.75 11 17.75H13.5C16.3995 17.75 18.75 15.3995 18.75 12.5C18.75 9.6005 16.3995 7.24999 13.5 7.24999H7.81067L8.53033 6.53033Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconUndoRec.isIcon = true;

export const IconUndoRec = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconUndoRec);
