// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconDollar(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M6 16C6 18.2091 7.79086 20 10 20H14.5132C16.4389 20 18 18.4389 18 16.5132C18 15.0123 17.0396 13.6799 15.6158 13.2053L8.3842 10.7947C6.96038 10.3201 6 8.98767 6 7.48683C6 5.56111 7.56111 4 9.48683 4H14C16.2091 4 18 5.79086 18 8M12 2L12 22"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconDollar.isIcon = true;

export const IconDollar = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconDollar);
