// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconCut(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <g clipPath="url(#clip0_2546_6083)">
        <path
          d="M7.57427 1.01762C7.30785 0.700459 6.83476 0.659321 6.5176 0.92574C6.20043 1.19216 6.15929 1.66525 6.42571 1.98241L9.78571 5.98241C10.0521 6.29958 10.5252 6.34072 10.8424 6.0743C11.1596 5.80788 11.2007 5.33479 10.9343 5.01762L7.57427 1.01762ZM18.0709 1.98637C18.3395 1.67105 18.3017 1.19769 17.9863 0.929086C17.671 0.660482 17.1977 0.698351 16.9291 1.01367L6.48471 13.2744C6.32534 13.2583 6.16363 13.25 6 13.25C3.37664 13.25 1.25 15.3766 1.25 18C1.25 20.6234 3.37664 22.75 6 22.75C8.62335 22.75 10.75 20.6234 10.75 18C10.75 16.1194 9.65712 14.4941 8.07182 13.7244L12.1936 8.88586L16.0029 13.689C14.3773 14.4433 13.25 16.09 13.25 18C13.25 20.6234 15.3766 22.75 18 22.75C20.6233 22.75 22.75 20.6234 22.75 18C22.75 15.3766 20.6233 13.25 18 13.25C17.8597 13.25 17.7208 13.2561 17.5836 13.268L13.185 7.722L18.0709 1.98637Z"
          fill="currentColor"
          fillRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="clip0_2546_6083">
          <rect height="24" width="24" fill="white" />
        </clipPath>
      </defs>
    </svg>
  );
}

_IconCut.isIcon = true;

export const IconCut = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  _IconCut,
);
