// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFire(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M5.1268 8.12818C4.19985 9.51259 3.25 11.5317 3.25 14C3.25 18.9625 7.08859 22.75 12 22.75C16.9114 22.75 20.75 18.9625 20.75 14C20.75 9.64303 18.6151 6.46256 16.5273 4.39847C14.9567 2.84572 13.1755 1.8378 11.25 0.811005C11.25 2.39337 13.1182 11.25 10 11.25C7.50784 11.25 8.25 6.63431 8.25 4.88539C7.03689 5.90944 6.04322 6.7595 5.1268 8.12818Z"
        fill="currentColor"
      />
    </svg>
  );
}

_IconFire.isIcon = true;

export const IconFire = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFire);
