// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFlag(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M5.75 2C5.75 1.58579 5.41421 1.25 5 1.25C4.58579 1.25 4.25 1.58579 4.25 2V4V16V22C4.25 22.4142 4.58579 22.75 5 22.75C5.41421 22.75 5.75 22.4142 5.75 22V16.75H20C20.2599 16.75 20.5013 16.6154 20.638 16.3943C20.7746 16.1732 20.7871 15.8971 20.6708 15.6646L19.1019 12.5268C18.5577 11.4384 18.3572 11.0222 18.2779 10.5993C18.2036 10.2032 18.2036 9.79678 18.2779 9.40071C18.3572 8.97777 18.5577 8.56158 19.1019 7.47324L20.6708 4.33541C20.7871 4.10292 20.7746 3.82681 20.638 3.6057C20.5013 3.38459 20.2599 3.25 20 3.25H5.75V2Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconFlag.isIcon = true;

export const IconFlag = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFlag);
