// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFlag3(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M5.75 2C5.75 1.58579 5.41421 1.25 5 1.25C4.58579 1.25 4.25 1.58579 4.25 2V4V16V22C4.25 22.4142 4.58579 22.75 5 22.75C5.41421 22.75 5.75 22.4142 5.75 22V16.218C6.36416 15.3085 7.30031 14.8059 8.51578 14.4918C9.49605 14.2384 10.5676 14.1265 11.7183 14.0064C12.124 13.964 12.5395 13.9206 12.9644 13.8697C14.5372 13.6809 16.2025 13.3878 17.6108 12.5706C19.0609 11.7291 20.1811 10.3681 20.7276 8.1819C20.7836 7.95785 20.7333 7.72048 20.5912 7.53844C20.449 7.3564 20.231 7.25 20 7.25C18.0652 7.25 16.7074 7.00853 15.6376 6.66158C14.5634 6.31317 13.749 5.84989 12.8721 5.34882L12.8546 5.33879C11.9864 4.84271 11.0551 4.31048 9.82513 3.91158C8.73787 3.55896 7.44054 3.31696 5.75 3.26192V2Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconFlag3.isIcon = true;

export const IconFlag3 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFlag3);
