// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFlag2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M5.75 2C5.75 1.58579 5.41421 1.25 5 1.25C4.58579 1.25 4.25 1.58579 4.25 2V4V15V22C4.25 22.4142 4.58579 22.75 5 22.75C5.41421 22.75 5.75 22.4142 5.75 22V15.5856L6.50141 15.3977C8.02473 15.0169 9.63694 15.2568 10.9834 16.0647C12.8409 17.1792 15.0927 17.4264 17.1477 16.7413L20.2372 15.7115C20.5434 15.6094 20.75 15.3228 20.75 15V4C20.75 3.75892 20.6341 3.53253 20.4385 3.39157C20.243 3.2506 19.9915 3.21225 19.7628 3.28849L16.6734 4.31831C15.0337 4.86486 13.2371 4.66764 11.7551 3.77842C10.0675 2.76589 8.04687 2.4652 6.13761 2.94252L5.75 3.03942V2Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconFlag2.isIcon = true;

export const IconFlag2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFlag2);
