// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconHome(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <g clipPath="url(#clip0_2546_6226)">
        <path
          d="M17.9971 3.83719C15.8568 2.12495 14.7866 1.26882 13.5998 0.940493C12.5529 0.650881 11.4471 0.650881 10.4002 0.940493C9.21339 1.26882 8.14324 2.12495 6.00293 3.83719L4.85293 4.75719C3.52983 5.81567 2.86828 6.34491 2.39209 7.00182C1.97024 7.58377 1.65638 8.23678 1.46548 8.92974C1.25 9.71194 1.25 10.5591 1.25 12.2535V17.5833C1.25 20.4368 3.5632 22.75 6.41667 22.75V22.75C7.8434 22.75 9 21.5934 9 20.1667V16C9 14.3431 10.3431 13 12 13V13C13.6569 13 15 14.3431 15 16V20.1667C15 21.5934 16.1566 22.75 17.5833 22.75V22.75C20.4368 22.75 22.75 20.4368 22.75 17.5833V12.2535C22.75 10.5591 22.75 9.71194 22.5345 8.92974C22.3436 8.23678 22.0298 7.58377 21.6079 7.00182C21.1317 6.34491 20.4702 5.81567 19.1471 4.75719L17.9971 3.83719Z"
          fill="currentColor"
        />
      </g>
      <defs>
        <clipPath id="clip0_2546_6226">
          <rect height="24" width="24" fill="white" />
        </clipPath>
      </defs>
    </svg>
  );
}

_IconHome.isIcon = true;

export const IconHome = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconHome);
