// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconMegaphone(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M20.75 4.62164C20.75 2.70623 20.75 1.74852 20.3654 1.22163C19.9971 0.717142 19.4143 0.413686 18.7898 0.401276C18.1375 0.388314 17.353 0.937523 15.7838 2.03594L12.115 4.60413C11.6153 4.95387 11.3655 5.12874 11.1849 5.3557C11.0251 5.55666 10.9054 5.78654 10.8324 6.03277C10.75 6.31085 10.75 6.61579 10.75 7.22567L10.75 14.7745C10.75 15.3843 10.75 15.6893 10.8324 15.9674C10.9054 16.2136 11.0251 16.4435 11.1849 16.6444C11.3655 16.8714 11.6153 17.0463 12.115 17.396L15.7837 19.9641C17.3529 21.0626 18.1376 21.6118 18.7898 21.5988C19.4143 21.5864 19.9971 21.283 20.3654 20.7785C20.75 20.2516 20.75 19.2939 20.75 17.3784V14.3005C20.75 14.1128 20.8438 13.9375 21 13.8334L21.752 13.3321C22.5317 12.8122 23 11.9371 23 11V11C23 10.0629 22.5317 9.18777 21.7519 8.66795L21 8.16672C20.8438 8.0626 20.75 7.88731 20.75 7.6996V4.62164Z"
        fill="currentColor"
      />
      <path
        d="M9.00761 6.25006C9.14149 6.25006 9.25003 6.3586 9.25003 6.49249V19.8751C9.25003 20.9106 8.41057 21.7501 7.37503 21.7501V21.7501C6.3395 21.7501 5.50003 20.9106 5.50003 19.8751V15.7501V15.7501C3.15282 15.7501 1.25003 13.8473 1.25003 11.5001L1.25003 11.0001C1.25003 8.37671 3.37668 6.25006 6.00003 6.25006H9.00761Z"
        fill="#2F384C"
      />
    </svg>
  );
}

_IconMegaphone.isIcon = true;

export const IconMegaphone = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconMegaphone);
