// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconMoreVert(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M11.5 7C12.875 7 14 5.875 14 4.5C14 3.125 12.875 2 11.5 2C10.125 2 9 3.125 9 4.5C9 5.875 10.125 7 11.5 7Z"
        fill="currentColor"
      />
      <path
        d="M11.5 9.5C10.125 9.5 9 10.625 9 12C9 13.375 10.125 14.5 11.5 14.5C12.875 14.5 14 13.375 14 12C14 10.625 12.875 9.5 11.5 9.5Z"
        fill="#2F384C"
      />
      <path
        d="M9 19.5C9 18.125 10.125 17 11.5 17C12.875 17 14 18.125 14 19.5C14 20.875 12.875 22 11.5 22C10.125 22 9 20.875 9 19.5Z"
        fill="#2F384C"
      />
    </svg>
  );
}

_IconMoreVert.isIcon = true;

export const IconMoreVert = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconMoreVert);
