// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconMoreHorizRec(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M4.52606 1.90396C5.80953 1.25 7.48969 1.25 10.85 1.25H13.15C16.5103 1.25 18.1905 1.25 19.4739 1.90396C20.6029 2.4792 21.5208 3.39709 22.096 4.52606C22.75 5.80953 22.75 7.48969 22.75 10.85V13.15C22.75 16.5103 22.75 18.1905 22.096 19.4739C21.5208 20.6029 20.6029 21.5208 19.4739 22.096C18.1905 22.75 16.5103 22.75 13.15 22.75H10.85C7.48969 22.75 5.80953 22.75 4.52606 22.096C3.39708 21.5208 2.4792 20.6029 1.90396 19.4739C1.25 18.1905 1.25 16.5103 1.25 13.15V10.85C1.25 7.48969 1.25 5.80953 1.90396 4.52606C2.4792 3.39708 3.39709 2.4792 4.52606 1.90396ZM5.75 12.25C5.75 13.0767 6.42329 13.75 7.25 13.75C8.07671 13.75 8.75 13.0767 8.75 12.25C8.75 11.4233 8.07671 10.75 7.25 10.75C6.42329 10.75 5.75 11.4233 5.75 12.25ZM10.25 12.25C10.25 13.0767 10.9233 13.75 11.75 13.75C12.5767 13.75 13.25 13.0767 13.25 12.25C13.25 11.4233 12.5767 10.75 11.75 10.75C10.9233 10.75 10.25 11.4233 10.25 12.25ZM15.25 12.25C15.25 13.0767 15.9233 13.75 16.75 13.75C17.5767 13.75 18.25 13.0767 18.25 12.25C18.25 11.4233 17.5767 10.75 16.75 10.75C15.9233 10.75 15.25 11.4233 15.25 12.25Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconMoreHorizRec.isIcon = true;

export const IconMoreHorizRec = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconMoreHorizRec);
