// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconNut(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M1.24973 11.105C1.24973 9.4533 1.24973 8.62744 1.48671 7.88537C1.69642 7.22868 2.03966 6.62246 2.49487 6.10477C3.00926 5.51977 3.71743 5.09487 5.13376 4.24507L7.88376 2.59507C9.38026 1.69717 10.1285 1.24822 10.9273 1.07281C11.6338 0.917651 12.3656 0.917651 13.0722 1.07281C13.8709 1.24822 14.6192 1.69717 16.1157 2.59507L18.8657 4.24507C20.282 5.09487 20.9902 5.51976 21.5046 6.10477C21.9598 6.62246 22.303 7.22868 22.5127 7.88537C22.7497 8.62744 22.7497 9.4533 22.7497 11.105V12.8953C22.7497 14.547 22.7497 15.3728 22.5127 16.1149C22.303 16.7716 21.9598 17.3778 21.5046 17.8955C20.9902 18.4805 20.282 18.9054 18.8657 19.7552L16.1157 21.4052C14.6192 22.3031 13.8709 22.752 13.0722 22.9275C12.3656 23.0826 11.6338 23.0826 10.9273 22.9275C10.1285 22.752 9.38026 22.3031 7.88376 21.4052L5.13376 19.7552C3.71743 18.9054 3.00926 18.4805 2.49487 17.8955C2.03966 17.3778 1.69642 16.7716 1.48671 16.1149C1.24973 15.3728 1.24973 14.547 1.24973 12.8952V11.105ZM12 8.99999C10.3432 8.99999 9.00001 10.3431 9.00001 12C9.00001 13.6568 10.3432 15 12 15C13.6569 15 15 13.6568 15 12C15 10.3431 13.6569 8.99999 12 8.99999Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconNut.isIcon = true;

export const IconNut = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  _IconNut,
);
