// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSortText(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M7 22L3 18M7 22L11 18M7 22V14M7 3V10M16 14H21L16 22H21M16 10V7M16 7V4.5C16 3.11929 17.1193 2 18.5 2C19.8807 2 21 3.11929 21 4.5V7M16 7H21M21 7V10"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconSortText.isIcon = true;

export const IconSortText = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSortText);
