// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconTag(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M9.59862 19.7502C8.51592 19.7502 7.97457 19.7502 7.47167 19.6172C7.02603 19.4993 6.60413 19.3052 6.2246 19.0436C5.79629 18.7483 5.44399 18.3373 4.73938 17.5153L3.58223 16.1653C2.31512 14.687 1.68157 13.9478 1.4401 13.1189C1.22728 12.3883 1.22728 11.6121 1.4401 10.8815C1.68157 10.0526 2.31512 9.31344 3.58223 7.83515L4.73937 6.48515C5.44399 5.6631 5.79629 5.25208 6.2246 4.95684C6.60413 4.69522 7.02603 4.50117 7.47167 4.38327C7.97457 4.25021 8.51592 4.25021 9.59862 4.25021H16.35C18.5902 4.25021 19.7103 4.25021 20.5659 4.68619C21.3186 5.06968 21.9305 5.6816 22.314 6.43425C22.75 7.2899 22.75 8.41 22.75 10.6502V13.3502C22.75 15.5904 22.75 16.7105 22.314 17.5662C21.9305 18.3188 21.3186 18.9307 20.5659 19.3142C19.7103 19.7502 18.5902 19.7502 16.35 19.7502L9.59862 19.7502ZM9.99986 14C11.1044 14 11.9999 13.1046 11.9999 12C11.9999 10.8954 11.1044 10 9.99986 10C8.8953 10 7.99987 10.8954 7.99987 12C7.99987 13.1046 8.8953 14 9.99986 14Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconTag.isIcon = true;

export const IconTag = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  _IconTag,
);
