// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconTerminal(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M4.52606 1.90396C5.80953 1.25 7.48968 1.25 10.85 1.25L13.15 1.25C16.5103 1.25 18.1905 1.25 19.4739 1.90396C20.6029 2.4792 21.5208 3.39709 22.096 4.52606C22.75 5.80953 22.75 7.48968 22.75 10.85L22.75 10.85L22.75 13.15C22.75 16.5103 22.75 18.1905 22.096 19.4739C21.5208 20.6029 20.6029 21.5208 19.4739 22.096C18.1905 22.75 16.5103 22.75 13.15 22.75L10.85 22.75C7.48968 22.75 5.80953 22.75 4.52605 22.096C3.39708 21.5208 2.4792 20.6029 1.90396 19.4739C1.25 18.1905 1.25 16.5103 1.25 13.15L1.25 10.85C1.25 7.48969 1.25 5.80953 1.90396 4.52606C2.4792 3.39709 3.39708 2.4792 4.52606 1.90396ZM7.53041 9.46991C7.23752 9.17702 6.76264 9.17702 6.46975 9.46991C6.17686 9.7628 6.17686 10.2377 6.46975 10.5306L8.93947 13.0003L6.46969 15.47C6.1768 15.7629 6.17679 16.2378 6.46968 16.5307C6.76257 16.8236 7.23745 16.8236 7.53034 16.5307L10.5305 13.5306C10.6711 13.39 10.7501 13.1992 10.7501 13.0003C10.7501 12.8014 10.6711 12.6106 10.5305 12.47L7.53041 9.46991ZM13.0001 15.2502C12.5859 15.2502 12.2501 15.586 12.2501 16.0002C12.2501 16.4145 12.5859 16.7502 13.0001 16.7502L17.0001 16.7502C17.4143 16.7502 17.7501 16.4145 17.7501 16.0002C17.7501 15.586 17.4143 15.2502 17.0001 15.2502L13.0001 15.2502Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconTerminal.isIcon = true;

export const IconTerminal = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconTerminal);
