// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconThumbsUp(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12.5264 0.412914C12.6307 0.308602 12.7722 0.25 12.9197 0.25C14.9163 0.25 16.2625 2.29148 15.476 4.12665L14.6374 6.08333C14.4007 6.63562 14.8058 7.25 15.4067 7.25H16.5272C18.9924 7.25 20.225 7.25 21.116 7.73236C21.9829 8.20166 22.646 8.97457 22.9781 9.90277C23.3193 10.8568 23.1319 12.0751 22.757 14.5116L22.4783 16.3232C22.182 18.2491 22.0339 19.2121 21.5618 19.9357C21.1457 20.5734 20.5562 21.0791 19.8627 21.3934C19.0757 21.75 18.1014 21.75 16.1528 21.75H10.65C8.40979 21.75 7.28968 21.75 6.43404 21.314C5.68139 20.9305 5.06947 20.3186 4.68597 19.566C4.25 18.7103 4.25 17.5902 4.25 15.35V12.6658C4.25 11.1982 4.25 10.4645 4.41578 9.77395C4.56276 9.16173 4.80519 8.57646 5.13416 8.03963C5.50521 7.43413 6.02407 6.91527 7.06178 5.87756L12.5264 0.412914ZM2.75 8C2.75 7.58579 2.41421 7.25 2 7.25C1.58579 7.25 1.25 7.58579 1.25 8V20C1.25 20.4142 1.58579 20.75 2 20.75C2.41421 20.75 2.75 20.4142 2.75 20L2.75 8Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconThumbsUp.isIcon = true;

export const IconThumbsUp = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconThumbsUp);
