// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconToggleOff(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M0.25 12C0.25 6.61522 4.61522 2.25 10 2.25H14C19.3848 2.25 23.75 6.61522 23.75 12V12C23.75 17.3848 19.3848 21.75 14 21.75H10C4.61522 21.75 0.25 17.3848 0.25 12V12ZM10 16C12.2091 16 14 14.2091 14 12C14 9.79086 12.2091 8 10 8C7.79086 8 6 9.79086 6 12C6 14.2091 7.79086 16 10 16Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconToggleOff.isIcon = true;

export const IconToggleOff = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconToggleOff);
