// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconUmbrella(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2.94296 7.68751C2.22494 9.25408 1.80412 10.8118 1.5624 11.972C1.25439 13.4504 2.47984 14.75 3.99 14.75H11.25V20C11.25 20.6904 10.6904 21.25 10 21.25C9.30964 21.25 8.75 20.6904 8.75 20V19C8.75 18.5858 8.41421 18.25 8 18.25C7.58578 18.25 7.25 18.5858 7.25 19V20C7.25 21.5188 8.48121 22.75 10 22.75C11.5188 22.75 12.75 21.5188 12.75 20V14.75H20.0095C21.5197 14.75 22.7451 13.4504 22.4371 11.972C22.1954 10.8118 21.7746 9.25408 21.0566 7.68751C19.6247 4.56337 16.9227 1.25 11.9998 1.25C7.07679 1.25 4.37485 4.56337 2.94296 7.68751Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconUmbrella.isIcon = true;

export const IconUmbrella = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconUmbrella);
