// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconWheelchair(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M21 22H20V22C18.8954 22 18 21.1046 18 20V19C18 18.0681 18 17.6022 17.8478 17.2346C17.6448 16.7446 17.2554 16.3552 16.7654 16.1522C16.3978 16 15.9319 16 15 16V16C14.0681 16 13.6022 16 13.2346 15.8478C12.7446 15.6448 12.3552 15.2554 12.1522 14.7654C12 14.3978 12 13.9319 12 13V12V9C12 10.6569 13.3431 12 15 12H16M9 10C5.68629 10 3 12.6863 3 16C3 19.3137 5.68629 22 9 22C10.777 22 12.3736 21.2275 13.4722 20M14 4C14 5.10457 13.1046 6 12 6C10.8954 6 10 5.10457 10 4C10 2.89543 10.8954 2 12 2C13.1046 2 14 2.89543 14 4Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconWheelchair.isIcon = true;

export const IconWheelchair = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconWheelchair);
