// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconWrench(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <g clipPath="url(#clip0_2546_6055)">
        <path
          d="M15.0001 1.25C10.7198 1.25 7.25005 4.71979 7.25005 9C7.25005 9.54962 7.2673 10.2289 7.34284 10.896V10.896C7.39227 11.3326 7.41699 11.5509 7.41932 11.6364C7.43566 12.236 7.33622 12.5204 6.94987 12.9792C6.89476 13.0446 6.79684 13.1426 6.60098 13.3384L1.96972 17.9697C0.848402 19.091 0.848402 20.909 1.96972 22.0303V22.0303C3.09104 23.1516 4.90906 23.1517 6.03038 22.0303L10.6616 17.3991C10.8575 17.2032 10.9554 17.1053 11.0209 17.0502C11.4796 16.6638 11.7641 16.5644 12.3636 16.5807C12.4491 16.5831 12.6674 16.6078 13.104 16.6572V16.6572C13.7712 16.7328 14.4504 16.75 15.0001 16.75C19.2803 16.75 22.7501 13.2802 22.7501 9C22.7501 8.62484 22.7233 8.25547 22.6716 7.8938L22.4593 6.40925L19.8723 8.99621C19.0803 9.78825 18.6842 10.1843 18.2276 10.3326C17.8259 10.4632 17.3932 10.4632 16.9915 10.3326C16.5349 10.1843 16.1388 9.78825 15.3468 8.99621L15.0038 8.65325C14.2118 7.86121 13.8158 7.4652 13.6674 7.00854C13.5369 6.60685 13.5369 6.17416 13.6674 5.77247C13.8158 5.31581 14.2118 4.9198 15.0038 4.12776L17.5908 1.54079L16.1063 1.32845C15.7446 1.27671 15.3752 1.25 15.0001 1.25Z"
          fill="currentColor"
        />
      </g>
      <defs>
        <clipPath id="clip0_2546_6055">
          <rect height="24" width="24" fill="white" />
        </clipPath>
      </defs>
    </svg>
  );
}

_IconWrench.isIcon = true;

export const IconWrench = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconWrench);
