// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconEdit2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M19.8499 2.79359C18.801 1.84011 17.1992 1.84008 16.1503 2.79353C16.1015 2.8379 16.0497 2.88975 15.9824 2.95709L15.9698 2.96966L8.72318 10.2162L8.67909 10.2603C8.25449 10.6848 7.98069 10.9585 7.75499 11.2725C7.55502 11.5506 7.38572 11.8496 7.25007 12.1642C7.09697 12.5193 7.00311 12.8949 6.85756 13.4774L6.84245 13.5379L6.27239 15.8181C6.2085 16.0737 6.28338 16.3441 6.46967 16.5303C6.65596 16.7166 6.92632 16.7915 7.1819 16.7276L9.46213 16.1576L9.52265 16.1424C10.1051 15.9969 10.4807 15.903 10.8358 15.7499C11.1504 15.6143 11.4494 15.445 11.7276 15.245C12.0415 15.0193 12.3152 14.7455 12.7397 14.3209L12.7838 14.2769L20.0304 7.03028L20.0429 7.01776L20.0429 7.01775C20.1103 6.95041 20.1621 6.89856 20.2065 6.84974C21.16 5.80088 21.16 4.19915 20.2066 3.15026C20.1622 3.10148 20.1104 3.04966 20.0431 2.98238L20.043 2.98231L20.0304 2.96972L20.0179 2.95715L20.0178 2.95712C19.9505 2.8898 19.8987 2.83794 19.8499 2.79359ZM4 20.25C3.58579 20.25 3.25 20.5858 3.25 21C3.25 21.4142 3.58579 21.75 4 21.75H20C20.4142 21.75 20.75 21.4142 20.75 21C20.75 20.5858 20.4142 20.25 20 20.25H4Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconEdit2.isIcon = true;

export const IconEdit2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconEdit2);
