// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconListUnordered5(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.5 5.5L5 4M5 4L6.5 2.5M5 4L3.5 2.5M5 4L6.5 5.5M3.5 13.5L5 12M5 12L6.5 10.5M5 12L3.5 10.5M5 12L6.5 13.5M3.5 21.5L5 20M5 20L6.5 18.5M5 20L3.5 18.5M5 20L6.5 21.5M11 20L22 20M11 12L22 12M11 4H22"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconListUnordered5.isIcon = true;

export const IconListUnordered5 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconListUnordered5);
