// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconListUnordered(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M9 20H22M9 12L22 12M9 4H22M3.5 4C3.5 4.27614 3.27614 4.5 3 4.5C2.72386 4.5 2.5 4.27614 2.5 4M3.5 4C3.5 3.72386 3.27614 3.5 3 3.5C2.72386 3.5 2.5 3.72386 2.5 4M3.5 4H2.5M3.5 12C3.5 12.2761 3.27614 12.5 3 12.5C2.72386 12.5 2.5 12.2761 2.5 12M3.5 12C3.5 11.7239 3.27614 11.5 3 11.5C2.72386 11.5 2.5 11.7239 2.5 12M3.5 12H2.5M3.5 20C3.5 20.2761 3.27614 20.5 3 20.5C2.72386 20.5 2.5 20.2761 2.5 20M3.5 20C3.5 19.7239 3.27614 19.5 3 19.5C2.72386 19.5 2.5 19.7239 2.5 20M3.5 20H2.5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconListUnordered.isIcon = true;

export const IconListUnordered = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconListUnordered);
