// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSpecialCharachersRec(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.98005 1.79497C5.04961 1.25 6.44974 1.25 9.25 1.25H14.75C17.5503 1.25 18.9504 1.25 20.02 1.79497C20.9608 2.27433 21.7257 3.03924 22.205 3.98005C22.75 5.04961 22.75 6.44974 22.75 9.25V14.75C22.75 17.5503 22.75 18.9504 22.205 20.02C21.7257 20.9608 20.9608 21.7257 20.02 22.205C18.9504 22.75 17.5503 22.75 14.75 22.75H9.25C6.44974 22.75 5.04961 22.75 3.98005 22.205C3.03924 21.7257 2.27433 20.9608 1.79497 20.02C1.25 18.9504 1.25 17.5503 1.25 14.75V9.25C1.25 6.44974 1.25 5.04961 1.79497 3.98005C2.27433 3.03924 3.03924 2.27433 3.98005 1.79497ZM6.75 11.8235C6.75 9.04244 9.07924 6.75 12 6.75C14.9208 6.75 17.25 9.04244 17.25 11.8235C17.25 13.774 16.109 15.4798 14.4151 16.3296C14.1044 16.4855 13.9415 16.8345 14.0217 17.1728C14.1018 17.5111 14.4038 17.75 14.7515 17.75H18C18.4142 17.75 18.75 17.4142 18.75 17C18.75 16.5858 18.4142 16.25 18 16.25H16.9901C18.0808 15.0846 18.75 13.533 18.75 11.8235C18.75 8.17212 15.7067 5.25 12 5.25C8.29334 5.25 5.25 8.17212 5.25 11.8235C5.25 13.533 5.91917 15.0846 7.00987 16.25H6C5.58579 16.25 5.25 16.5858 5.25 17C5.25 17.4142 5.58579 17.75 6 17.75H9.24853C9.59617 17.75 9.89824 17.5111 9.97835 17.1728C10.0585 16.8345 9.8956 16.4855 9.58488 16.3296C7.89101 15.4798 6.75 13.774 6.75 11.8235Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconSpecialCharachersRec.isIcon = true;

export const IconSpecialCharachersRec = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSpecialCharachersRec);
