// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSpecialCharachers(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 21H7.41422C4.19827 19.3277 2 15.9515 2 12.0588C2 6.50349 6.47715 2 12 2C17.5228 2 22 6.50349 22 12.0588C22 15.9515 19.8017 19.3277 16.5858 21H22"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconSpecialCharachers.isIcon = true;

export const IconSpecialCharachers = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSpecialCharachers);
