// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./users.tsx";
export * from "./user.tsx";
export * from "./user-square.tsx";
export * from "./user-plus.tsx";
export * from "./user-minus.tsx";
export * from "./user-cross.tsx";
export * from "./user-circle.tsx";
export * from "./user-check.tsx";
export * from "./user-arrow-tr.tsx";
export * from "./user-arrow-top.tsx";
export * from "./user-arrow-right.tsx";
export * from "./user-arrow-bottom.tsx";
export * from "./user-arrow-bl.tsx";
export * from "./user-alert.tsx";
