// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconBulb(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M9 18C9 18 10 18.5 12 18.5M12 18.5C14 18.5 15 18 15 18M12 18.5V14M20 10C20 5.58172 16.4183 2 12 2C7.58172 2 4 5.58172 4 10C4 12.9482 6.2263 15.3013 7.70778 16.5408C8.47633 17.1838 9 18.1102 9 19.1123V19.1123C9 20.7071 10.2929 22 11.8877 22H12.1268C13.7136 22 15 20.7136 15 19.1268V19.1268C15 18.1175 15.5342 17.1861 16.3119 16.5427C17.7933 15.317 20 12.9895 20 10Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconBulb.isIcon = true;

export const IconBulb = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconBulb);
