// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconDevices(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M19 12H19.01M19 21H4.55556C2.59188 21 1 19.4081 1 17.4444V17.4444C1 17.199 1.19898 17 1.44444 17H15M3 17V9.4C3 7.15979 3 6.03968 3.43597 5.18404C3.81947 4.43139 4.43139 3.81947 5.18404 3.43597C6.03968 3 7.15979 3 9.4 3H18.5C19.8807 3 21 4.11929 21 5.5V5.5V6M19.5 12C19.5 12.2761 19.2761 12.5 19 12.5C18.7239 12.5 18.5 12.2761 18.5 12C18.5 11.7239 18.7239 11.5 19 11.5C19.2761 11.5 19.5 11.7239 19.5 12ZM18.2 21H19.8C20.9201 21 21.4802 21 21.908 20.782C22.2843 20.5903 22.5903 20.2843 22.782 19.908C23 19.4802 23 18.9201 23 17.8V12.2C23 11.0799 23 10.5198 22.782 10.092C22.5903 9.71569 22.2843 9.40973 21.908 9.21799C21.4802 9 20.9201 9 19.8 9H18.2C17.0799 9 16.5198 9 16.092 9.21799C15.7157 9.40973 15.4097 9.71569 15.218 10.092C15 10.5198 15 11.0799 15 12.2V17.8C15 18.9201 15 19.4802 15.218 19.908C15.4097 20.2843 15.7157 20.5903 16.092 20.782C16.5198 21 17.0799 21 18.2 21Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconDevices.isIcon = true;

export const IconDevices = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconDevices);
