// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconGlassesVr(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M21.9996 14V6.71259C21.9996 6.08645 21.9996 5.77337 21.9133 5.4892C21.8369 5.23762 21.7117 5.00357 21.5447 4.80045C21.3561 4.57101 21.0957 4.39735 20.5747 4.05003L18.9996 3M1.99963 14V6.71259C1.99963 6.08645 1.99963 5.77337 2.08594 5.4892C2.16234 5.23762 2.2876 5.00357 2.45454 4.80045C2.64312 4.57101 2.90361 4.39735 3.42459 4.05003L4.99963 3M10 15C10 16.1046 9.10457 17 8 17C6.89543 17 6 16.1046 6 15C6 13.8954 6.89543 13 8 13C9.10457 13 10 13.8954 10 15ZM18 15C18 16.1046 17.1046 17 16 17C14.8954 17 14 16.1046 14 15C14 13.8954 14.8954 13 16 13C17.1046 13 18 13.8954 18 15ZM8 21H16C16.929 21 17.3935 21 17.7822 20.9384C19.9216 20.5996 21.5996 18.9216 21.9384 16.7822C22 16.3935 22 15.929 22 15V15C22 14.071 22 13.6065 21.9384 13.2178C21.5996 11.0784 19.9216 9.40042 17.7822 9.06156C17.3935 9 16.929 9 16 9H8C7.07099 9 6.60649 9 6.21783 9.06156C4.07837 9.40042 2.40042 11.0784 2.06156 13.2178C2 13.6065 2 14.071 2 15V15C2 15.929 2 16.3935 2.06156 16.7822C2.40042 18.9216 4.07837 20.5996 6.21783 20.9384C6.60649 21 7.07099 21 8 21Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconGlassesVr.isIcon = true;

export const IconGlassesVr = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconGlassesVr);
