// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconHardDrive(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 17V15.5467C2 15.3419 2 15.2396 2.00694 15.1377C2.01311 15.0472 2.02338 14.957 2.03773 14.8674C2.05387 14.7666 2.07689 14.6668 2.12292 14.4673L3.85518 6.9609C4.26393 5.18963 4.46831 4.30399 4.94994 3.64343C5.37479 3.06072 5.94928 2.60371 6.6126 2.32076C7.36455 2 8.27346 2 10.0913 2H13.9087C15.7265 2 16.6355 2 17.3874 2.32076C18.0507 2.60371 18.6252 3.06072 19.0501 3.64343C19.5317 4.30399 19.7361 5.18963 20.1448 6.9609L21.8771 14.4673C21.9231 14.6668 21.9461 14.7666 21.9623 14.8674C21.9766 14.957 21.9869 15.0472 21.9931 15.1377C22 15.2396 22 15.3419 22 15.5467V17M11 18H17M7 18H7.01M7.5 18C7.5 18.2761 7.27614 18.5 7 18.5C6.72386 18.5 6.5 18.2761 6.5 18C6.5 17.7239 6.72386 17.5 7 17.5C7.27614 17.5 7.5 17.7239 7.5 18ZM6 22H18C18.93 22 19.395 22 19.7765 21.8978C20.8117 21.6204 21.6204 20.8117 21.8978 19.7765C22 19.395 22 18.93 22 18V18C22 17.07 22 16.605 21.8978 16.2235C21.6204 15.1883 20.8117 14.3796 19.7765 14.1022C19.395 14 18.93 14 18 14H6C5.07003 14 4.60504 14 4.22354 14.1022C3.18827 14.3796 2.37962 15.1883 2.10222 16.2235C2 16.605 2 17.07 2 18V18C2 18.93 2 19.395 2.10222 19.7765C2.37962 20.8117 3.18827 21.6204 4.22354 21.8978C4.60504 22 5.07003 22 6 22Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconHardDrive.isIcon = true;

export const IconHardDrive = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconHardDrive);
