// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconPlugSlash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M8 2V4M16 7V2M22 22L19.7164 19.7088L19.7131 19.7131M3 3L7.00664 7.00664L7.02558 7.02558M11 7H15C16.8638 7 17.7956 7 18.5307 7.30448C19.5108 7.71046 20.2895 8.48915 20.6955 9.46927C21 10.2044 21 11.1362 21 13C21 14.8284 21 16.0589 20.8722 17M7.02558 7.02558C6.35766 7.05841 5.88239 7.13336 5.46927 7.30448C4.48915 7.71046 3.71046 8.48915 3.30448 9.46927C3 10.2044 3 11.1362 3 13C3 15.7957 3 17.1935 3.45672 18.2961C4.06569 19.7663 5.23373 20.9343 6.7039 21.5433C7.80653 22 9.20435 22 12 22C14.7956 22 16.1935 22 17.2961 21.5433C18.2536 21.1467 19.0829 20.513 19.7131 19.7131M7.02558 7.02558L19.7131 19.7131"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconPlugSlash.isIcon = true;

export const IconPlugSlash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconPlugSlash);
