// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconWeighter(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 13H14.5878C15.1018 13 15.3588 13 15.588 12.9243C15.7907 12.8573 15.9769 12.7478 16.1339 12.6031C16.3114 12.4395 16.4362 12.2148 16.6858 11.7655L17.201 10.8381C17.4547 10.3816 17.5815 10.1533 17.601 9.8102C17.6147 9.56905 17.512 9.15574 17.387 8.94906C17.2092 8.655 17.053 8.55346 16.7407 8.35038C15.7477 7.70469 14.1675 7 12 7C9.83252 7 8.25229 7.70469 7.2593 8.35038C6.94698 8.55346 6.79082 8.655 6.61302 8.94906C6.48804 9.15574 6.38533 9.56905 6.39902 9.8102C6.41849 10.1533 6.54531 10.3816 6.79896 10.8381L7.31419 11.7655C7.56379 12.2148 7.6886 12.4395 7.8661 12.6031C8.02314 12.7478 8.20926 12.8573 8.41202 12.9243C8.64122 13 8.8982 13 9.41217 13H12ZM12 13L10 10M10 17H14M11.6 22H12.4C15.7603 22 17.4405 22 18.7239 21.346C19.8529 20.7708 20.7708 19.8529 21.346 18.7239C22 17.4405 22 15.7603 22 12.4V11.6C22 8.23969 22 6.55953 21.346 5.27606C20.7708 4.14708 19.8529 3.2292 18.7239 2.65396C17.4405 2 15.7603 2 12.4 2H11.6C8.23969 2 6.55953 2 5.27606 2.65396C4.14708 3.2292 3.2292 4.14708 2.65396 5.27606C2 6.55953 2 8.23969 2 11.6V12.4C2 15.7603 2 17.4405 2.65396 18.7239C3.2292 19.8529 4.14708 20.7708 5.27606 21.346C6.55953 22 8.23969 22 11.6 22Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconWeighter.isIcon = true;

export const IconWeighter = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconWeighter);
