// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFirstLine3(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M6.00024 9.00003V3.00003M6.00024 3.00003H9.00024M6.00024 3.00003H3.00024M3.00024 21H21.0002M13.0002 3.00003L21.0002 3.00003M13.0002 9.00003L21.0002 9.00003M3.00024 15H21.0002"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconFirstLine3.isIcon = true;

export const IconFirstLine3 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFirstLine3);
