// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFirstLine2(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.00024 21.0001H21.0002M13.0002 3.00006L21.0002 3.00006M13.0002 9.00006L21.0002 9.00006M3.00024 15.0001H21.0002M9.00024 6.00006C9.00024 7.65692 7.6571 9.00006 6.00024 9.00006C4.34339 9.00006 3.00024 7.65692 3.00024 6.00006C3.00024 4.34321 4.34339 3.00006 6.00024 3.00006C7.6571 3.00006 9.00024 4.34321 9.00024 6.00006Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconFirstLine2.isIcon = true;

export const IconFirstLine2 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFirstLine2);
