// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconIndentFirstLine(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.00024 21.0002H21.0002M12.0002 3.00018L21.0002 3.00018M12.0002 9.00018L21.0002 9.00018M4.00024 3.00018L7.00024 6.00018L4.00024 9.00018M3.00024 15.0002H21.0002"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconIndentFirstLine.isIcon = true;

export const IconIndentFirstLine = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconIndentFirstLine);
