// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconListUnordered4(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M11.0002 20.0002L22.0002 20.0002M11.0002 12.0002L22.0002 12.0002M11.0002 4.0002H22.0002M2.00024 4.0002L3.00024 5.0002L6.00024 2.0002M2.00024 12.0002L3.00024 13.0002L6.00024 10.0002M2.00024 20.0002L3.00024 21.0002L6.00024 18.0002"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconListUnordered4.isIcon = true;

export const IconListUnordered4 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconListUnordered4);
