// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconListUnordered3(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M11.0002 20L22.0002 20M11.0002 12L22.0002 12M11.0002 4.00002H22.0002M6.00024 4.00002C6.00024 5.10458 5.10481 6.00002 4.00024 6.00002C2.89567 6.00002 2.00024 5.10458 2.00024 4.00002C2.00024 2.89545 2.89567 2.00002 4.00024 2.00002C5.10481 2.00002 6.00024 2.89545 6.00024 4.00002ZM6.00024 12C6.00024 13.1046 5.10481 14 4.00024 14C2.89567 14 2.00024 13.1046 2.00024 12C2.00024 10.8954 2.89567 10 4.00024 10C5.10481 10 6.00024 10.8954 6.00024 12ZM6.00024 20C6.00024 21.1046 5.10481 22 4.00024 22C2.89567 22 2.00024 21.1046 2.00024 20C2.00024 18.8954 2.89567 18 4.00024 18C5.10481 18 6.00024 18.8954 6.00024 20Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconListUnordered3.isIcon = true;

export const IconListUnordered3 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconListUnordered3);
