// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconListUnordered5(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.50024 5.50014L5.00024 4.00014M5.00024 4.00014L6.50024 2.50014M5.00024 4.00014L3.50024 2.50014M5.00024 4.00014L6.50024 5.50014M3.50024 13.5001L5.00024 12.0001M5.00024 12.0001L6.50024 10.5001M5.00024 12.0001L3.50024 10.5001M5.00024 12.0001L6.50024 13.5001M3.50024 21.5001L5.00024 20.0001M5.00024 20.0001L6.50024 18.5001M5.00024 20.0001L3.50024 18.5001M5.00024 20.0001L6.50024 21.5001M11.0002 20.0001L22.0002 20.0001M11.0002 12.0001L22.0002 12.0001M11.0002 4.00014H22.0002"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconListUnordered5.isIcon = true;

export const IconListUnordered5 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconListUnordered5);
