// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconListOrdered(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M9.00024 20.0001H22.0002M9.00024 12.0001L22.0002 12.0001M9.00024 4.00014H22.0002M3.50024 8.00014V3.00014L2.00024 4.00008M3.50024 8.00014H2.00024M3.50024 8.00014L5.00024 8.00008M2.00049 15.0001H5.00049L5.00024 17.5001H2.00024V20.0001H5.00049"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconListOrdered.isIcon = true;

export const IconListOrdered = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconListOrdered);
