// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconPaintTool(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M17 5H17.8C18.9201 5 19.4802 5 19.908 5.21799C20.2843 5.40973 20.5903 5.71569 20.782 6.09202C21 6.51984 21 7.07989 21 8.2V8.8C21 9.9201 21 10.4802 20.782 10.908C20.5903 11.2843 20.2843 11.5903 19.908 11.782C19.4802 12 18.9201 12 17.8 12H14.2C13.0799 12 12.5198 12 12.092 12.218C11.7157 12.4097 11.4097 12.7157 11.218 13.092C11 13.5198 11 14.0799 11 15.2V16M11 22V22C12.1046 22 13 21.1046 13 20V18C13 16.8954 12.1046 16 11 16V16C9.89543 16 9 16.8954 9 18V20C9 21.1046 9.89543 22 11 22ZM8 8H14C14.9319 8 15.3978 8 15.7654 7.84776C16.2554 7.64477 16.6448 7.25542 16.8478 6.76537C17 6.39782 17 5.93188 17 5V5C17 4.06812 17 3.60218 16.8478 3.23463C16.6448 2.74458 16.2554 2.35523 15.7654 2.15224C15.3978 2 14.9319 2 14 2H8C7.06812 2 6.60218 2 6.23463 2.15224C5.74458 2.35523 5.35523 2.74458 5.15224 3.23463C5 3.60218 5 4.06812 5 5V5C5 5.93188 5 6.39782 5.15224 6.76537C5.35523 7.25542 5.74458 7.64477 6.23463 7.84776C6.60218 8 7.06812 8 8 8Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconPaintTool.isIcon = true;

export const IconPaintTool = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconPaintTool);
