// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconPaperclip2Slash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M20 5V14.5C20 14.8391 19.9775 15.1729 19.9339 15.5M2 2L5.29737 5.29737M22 22L18.7087 18.7087M5.29737 5.29737C5.10493 5.8288 5 6.40215 5 7V14.5C5 18.6421 8.35786 22 12.5 22C15.0822 22 17.3596 20.6951 18.7087 18.7087M5.29737 5.29737L10 10M18.7087 18.7087L14.9581 14.9581M15 11V7C15 4.23858 12.7614 2 10 2C8.87418 2 7.83526 2.37209 6.99951 3M14.9581 14.9581C14.7429 16.12 13.7242 17 12.5 17C11.1193 17 10 15.8807 10 14.5V10M14.9581 14.9581L10 10"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconPaperclip2Slash.isIcon = true;

export const IconPaperclip2Slash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconPaperclip2Slash);
