// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconPrinterSlash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M8 8H7C5.13077 8 4.19615 8 3.5 8.40192C3.04394 8.66523 2.66523 9.04394 2.40192 9.5C2 10.1962 2 11.1308 2 13V14C2 14.93 2 15.395 2.10222 15.7765C2.37962 16.8117 3.18827 17.6204 4.22354 17.8978C4.60504 18 5.07003 18 6 18M8 8L2 2M8 8L18 18M18 18L22 22M18 18V18.8C18 19.9201 18 20.4802 17.782 20.908C17.5903 21.2843 17.2843 21.5903 16.908 21.782C16.4802 22 15.9201 22 14.8 22H9C8.06812 22 7.60218 22 7.23463 21.8478C6.74458 21.6448 6.35523 21.2554 6.15224 20.7654C6 20.3978 6 19.9319 6 19C6 18.0681 6 17.6022 6.15224 17.2346C6.35523 16.7446 6.74458 16.3552 7.23463 16.1522C7.60218 16 8.06812 16 9 16H16M21.2361 17C21.5444 16.6553 21.774 16.2385 21.8978 15.7765C22 15.395 22 14.93 22 14V13C22 11.1308 22 10.1962 21.5981 9.5C21.3348 9.04394 20.9561 8.66523 20.5 8.40192C19.8038 8 18.8692 8 17 8H12M18 8V5.2C18 4.0799 18 3.51984 17.782 3.09202C17.5903 2.71569 17.2843 2.40973 16.908 2.21799C16.4802 2 15.9201 2 14.8 2H8M5 11H6"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconPrinterSlash.isIcon = true;

export const IconPrinterSlash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconPrinterSlash);
