// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconQuotes(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M10 8V13.25C10 13.9821 10 14.3481 9.95974 14.6939C9.79723 16.0896 9.15003 17.384 8.13097 18.3514C7.8785 18.5911 7.58567 18.8107 7 19.25V19.25L6 20M22 8V13.25C22 13.9821 22 14.3481 21.9597 14.6939C21.7972 16.0896 21.15 17.384 20.131 18.3514C19.8785 18.5911 19.5857 18.8107 19 19.25V19.25L18 20M17.2 12H18.8C19.9201 12 20.4802 12 20.908 11.782C21.2843 11.5903 21.5903 11.2843 21.782 10.908C22 10.4802 22 9.92011 22 8.8V7.2C22 6.07989 22 5.51984 21.782 5.09202C21.5903 4.71569 21.2843 4.40973 20.908 4.21799C20.4802 4 19.9201 4 18.8 4H17.2C16.0799 4 15.5198 4 15.092 4.21799C14.7157 4.40973 14.4097 4.71569 14.218 5.09202C14 5.51984 14 6.07989 14 7.2V8.8C14 9.92011 14 10.4802 14.218 10.908C14.4097 11.2843 14.7157 11.5903 15.092 11.782C15.5198 12 16.0799 12 17.2 12ZM5.2 12H6.8C7.92011 12 8.48016 12 8.90798 11.782C9.28431 11.5903 9.59027 11.2843 9.78201 10.908C10 10.4802 10 9.92011 10 8.8V7.2C10 6.07989 10 5.51984 9.78201 5.09202C9.59027 4.71569 9.28431 4.40973 8.90798 4.21799C8.48016 4 7.92011 4 6.8 4H5.2C4.07989 4 3.51984 4 3.09202 4.21799C2.71569 4.40973 2.40973 4.71569 2.21799 5.09202C2 5.51984 2 6.07989 2 7.2V8.8C2 9.92011 2 10.4802 2.21799 10.908C2.40973 11.2843 2.71569 11.5903 3.09202 11.782C3.51984 12 4.07989 12 5.2 12Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconQuotes.isIcon = true;

export const IconQuotes = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconQuotes);
