// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconText(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 3V21M12 3H6.4C5.55992 3 5.13988 3 4.81901 3.16349C4.53677 3.3073 4.3073 3.53677 4.16349 3.81901C4 4.13988 4 4.55992 4 5.4V5.5V6M12 3H17.6C18.4401 3 18.8601 3 19.181 3.16349C19.4632 3.3073 19.6927 3.53677 19.8365 3.81901C20 4.13988 20 4.55992 20 5.4V5.5V6M12 21H17M12 21H7"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconText.isIcon = true;

export const IconText = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconText);
