// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconWrapText(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3.00024 19.0002H7.00024M3.00024 11.0002L18.0002 11.0002C20.2094 11.0002 22.0002 12.791 22.0002 15.0002V15.0002C22.0002 17.2093 20.2094 19.0002 18.0002 19.0002L12.0002 19.0002M12.0002 19.0002L15.0002 16.0002M12.0002 19.0002L15.0002 22.0002M3.00024 3.00018H21.0002"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconWrapText.isIcon = true;

export const IconWrapText = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconWrapText);
