// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconMic(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 1.25A5.75 5.75 0 006.25 7v4a5.75 5.75 0 0011.5 0V7c0-.816-.17-1.595-.479-2.3a.75.75 0 10-1.374.6c.227.52.353 1.094.353 1.7v4a4.25 4.25 0 01-8.5 0V7a4.25 4.25 0 015.95-3.897.75.75 0 00.6-1.374A5.733 5.733 0 0012 1.25zM4.75 11a.75.75 0 00-1.5 0c0 3.98 2.632 6.777 5.449 8.013A.75.75 0 109.3 17.64C6.886 16.58 4.75 14.242 4.75 11zm16 0a.75.75 0 00-1.5 0c0 2.252-1.024 4.056-2.458 5.31-1.448 1.268-3.277 1.94-4.792 1.94a.75.75 0 00-.75.75v3a.75.75 0 001.5 0v-2.29c1.714-.184 3.553-.979 5.03-2.27 1.709-1.496 2.97-3.692 2.97-6.44z"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconMic.isIcon = true;

export const IconMic = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  _IconMic,
);
