// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconMouse = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconMouse(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M12 1.25A8.75 8.75 0 003.25 10v4a8.75 8.75 0 1017.5 0v-4a8.716 8.716 0 00-1.92-5.47.75.75 0 00-1.17.94A7.216 7.216 0 0119.25 10v4a7.25 7.25 0 11-14.5 0v-4a7.25 7.25 0 019.969-6.723.75.75 0 10.562-1.39A8.727 8.727 0 0012 1.25zM12.75 8a.75.75 0 00-1.5 0v2a.75.75 0 001.5 0V8z"
        fillRule="evenodd"
      />
    </svg>
  );
});
