// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./you-tube.tsx";
export * from "./x.tsx";
export * from "./whats-app.tsx";
export * from "./vk.tsx";
export * from "./twitch.tsx";
export * from "./tumblr.tsx";
export * from "./tik-tok.tsx";
export * from "./threads.tsx";
export * from "./telegram.tsx";
export * from "./spotify.tsx";
export * from "./snapchat.tsx";
export * from "./signal.tsx";
export * from "./reddit.tsx";
export * from "./pinterest.tsx";
export * from "./messenger.tsx";
export * from "./medium.tsx";
export * from "./linked-in.tsx";
export * from "./instagram.tsx";
export * from "./google.tsx";
export * from "./github.tsx";
export * from "./figma.tsx";
export * from "./facebook.tsx";
export * from "./dribbble.tsx";
export * from "./discord.tsx";
export * from "./clubhouse.tsx";
export * from "./apple.tsx";
