import Head from "next/head";
import AssetsTable from "../src/components/asset/AssetsTable";
import Container from "../src/components/Container";
import Header from "../src/components/Header";
import Snackbar from "../src/components/notification/Snackbar";
import { WalletContext } from "../src/components/wallet/WalletContext";

export default function Home() {
  return (
    <WalletContext>
      <>
        <Head>
          <title>Assets Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Container>
            <>
              <Header />
              <div className="container mx-auto">
                <AssetsTable />
                <div className="flex flex-col fixed left-6 bottom-6 z-[100] space-y-5">
                  {/* TODO: delete the snackbar in the list, not only apply hidden prop */}
                  {/* estado si esta mostrando o no. antes de agregar una asnackbar nueva,
                  borro todos las nacksbars que esten en hidden. */}
                  <Snackbar type="success" text="Text" subtext="subtext" />
                  <Snackbar type="error" text="Text" subtext="subtext" />
                  <Snackbar type="default" text="Text" subtext="subtext" />
                </div>
              </div>
            </>
          </Container>
        </main>
        {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      </>
    </WalletContext>
  );
}
