import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";
import AssetsTable from "../src/components/asset/AssetsTable";
import Container from "../src/components/Container";
import Header from "../src/components/Header";
import { WalletContext } from "../src/components/wallet/WalletContext";

export default function Home() {
  // Create a client
  const queryClient = new QueryClient();
  return (
    <WalletContext>
      <QueryClientProvider client={queryClient}>
        <>
          <Head>
            <title>Assets Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <Container>
              <>
                <Header />
                <div className="container mx-auto">
                  <AssetsTable />
                </div>
              </>
            </Container>
          </main>
        </>
      </QueryClientProvider>
    </WalletContext>
  );
}
