// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconFastRewind(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2.80048 14.692C1.40694 13.7961 0.710166 13.3482 0.469506 12.7787C0.259227 12.281 0.259227 11.7194 0.469506 11.2218C0.710166 10.6522 1.40694 10.2043 2.80048 9.30844L10.4243 4.40743C11.5003 3.71569 12.0383 3.36983 12.4735 3.30903C13.3466 3.18706 14.1965 3.6511 14.566 4.45145C14.7502 4.85039 14.7502 5.48998 14.7502 6.76918V6.76918L17.8196 4.79602C19.4255 3.76364 20.2285 3.24745 20.8925 3.29488C21.4711 3.33621 22.0034 3.62676 22.351 4.09117C22.75 4.62409 22.75 5.57866 22.75 7.48779V16.5126C22.75 18.4218 22.75 19.3763 22.351 19.9093C22.0034 20.3737 21.4711 20.6642 20.8925 20.7056C20.2285 20.753 19.4255 20.2368 17.8196 19.2044L14.7502 17.2313V17.2313C14.7502 18.5104 14.7502 19.15 14.566 19.549C14.1965 20.3493 13.3466 20.8134 12.4735 20.6914C12.0383 20.6306 11.5003 20.2847 10.4243 19.593L2.80048 14.692Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconFastRewind.isIcon = true;

export const IconFastRewind = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconFastRewind);
