// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconMusicNote3(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M19.364 9.1821L9.75 11.5856V19C9.75 21.0711 8.07107 22.75 6 22.75C3.92893 22.75 2.25 21.0711 2.25 19C2.25 16.9289 3.92893 15.25 6 15.25C6.8442 15.25 7.62325 15.529 8.25 15.9997V11V6.72438L8.25 6.69955V6.69953C8.24999 6.38128 8.24998 6.10331 8.26693 5.8709C8.285 5.62302 8.32482 5.3772 8.42929 5.13141C8.58746 4.7593 8.84298 4.43668 9.16897 4.19749C9.3843 4.0395 9.61447 3.94444 9.85161 3.87007C10.074 3.80034 10.3446 3.73668 10.6544 3.6638L10.6785 3.65811L17.8785 1.964L17.9103 1.95651C18.3868 1.8444 18.7916 1.74913 19.1258 1.70096C19.4733 1.65088 19.8296 1.63708 20.1853 1.75081C20.7058 1.91725 21.148 2.26745 21.4292 2.73602C21.6214 3.05619 21.6895 3.40618 21.7204 3.75589C21.75 4.09227 21.75 4.50812 21.75 4.99753V5.03026V6.12615L21.7501 6.24402C21.751 6.79509 21.7518 7.27811 21.5744 7.70036C21.4194 8.06922 21.1689 8.39009 20.8486 8.6299C20.482 8.90442 20.0132 9.02083 19.4784 9.15363L19.364 9.1821Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconMusicNote3.isIcon = true;

export const IconMusicNote3 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconMusicNote3);
