// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconPlaylistPlay(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 3.25C1.58579 3.25 1.25 3.58579 1.25 4C1.25 4.41421 1.58579 4.75 2 4.75H20C20.4142 4.75 20.75 4.41421 20.75 4C20.75 3.58579 20.4142 3.25 20 3.25H2ZM2 8.25C1.58579 8.25 1.25 8.58579 1.25 9C1.25 9.41421 1.58579 9.75 2 9.75H16C16.4142 9.75 16.75 9.41421 16.75 9C16.75 8.58579 16.4142 8.25 16 8.25H2ZM2 13.25C1.58579 13.25 1.25 13.5858 1.25 14C1.25 14.4142 1.58579 14.75 2 14.75H11C11.4142 14.75 11.75 14.4142 11.75 14C11.75 13.5858 11.4142 13.25 11 13.25H2ZM2 18.25C1.58579 18.25 1.25 18.5858 1.25 19C1.25 19.4142 1.58579 19.75 2 19.75H9C9.41421 19.75 9.75 19.4142 9.75 19C9.75 18.5858 9.41421 18.25 9 18.25H2ZM18.235 13.5886L18.235 13.5886L20.9558 15.4025C21.757 15.9366 22.1576 16.2037 22.2972 16.5403C22.4193 16.8346 22.4193 17.1654 22.2972 17.4597C22.1576 17.7963 21.757 18.0634 20.9558 18.5975L18.235 20.4114C17.2654 21.0578 16.7805 21.381 16.3785 21.357C16.0282 21.3361 15.7047 21.163 15.493 20.8831C15.25 20.5619 15.25 19.9792 15.25 18.8138V15.1862C15.25 14.0208 15.25 13.4381 15.493 13.1169C15.7047 12.837 16.0282 12.6639 16.3785 12.643C16.7805 12.619 17.2653 12.9422 18.235 13.5886Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconPlaylistPlay.isIcon = true;

export const IconPlaylistPlay = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconPlaylistPlay);
