name: "Install & Cache Dependencies"
steps:
  - name: Cache Dependencies
    uses: actions/cache@v3
    id: cache-dependencies
    with:
      path: |
        **/node_modules
      key: dependencies-turbo-${{ hashFiles('**/yarn.lock') }}-v1
  - name: Install Dependencies
    if: steps.cache-dependencies.outputs.cache-hit != 'true'
    run: yarn install
