// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconCompass(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M9.75515 12.1387C10.0308 11.5323 10.1686 11.2291 10.3627 10.9694C10.5348 10.7392 10.7392 10.5348 10.9694 10.3627C11.2291 10.1686 11.5323 10.0308 12.1387 9.75515L16 8L14.2448 11.8613C13.9692 12.4677 13.8314 12.7709 13.6373 13.0306C13.4652 13.2608 13.2608 13.4652 13.0306 13.6373C12.7709 13.8314 12.4677 13.9692 11.8613 14.2448L8 16L9.75515 12.1387Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
      <path
        d="M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconCompass.isIcon = true;

export const IconCompass = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconCompass);
