// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./lightning.tsx";
export * from "./lightning-slash.tsx";
export * from "./image.tsx";
export * from "./image-upload.tsx";
export * from "./image-slash.tsx";
export * from "./image-plus.tsx";
export * from "./image-edit.tsx";
export * from "./image-download.tsx";
export * from "./image-cross.tsx";
export * from "./image-check.tsx";
export * from "./image-3.tsx";
export * from "./image-2.tsx";
export * from "./color-filter.tsx";
export * from "./camera.tsx";
export * from "./camera-slash.tsx";
export * from "./apperture.tsx";
