// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconUserCross(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M9 1.25C6.37665 1.25 4.25 3.37665 4.25 6C4.25 8.62335 6.37665 10.75 9 10.75C11.6234 10.75 13.75 8.62335 13.75 6C13.75 3.37665 11.6234 1.25 9 1.25ZM1.25 18.95C1.25 15.802 3.80198 13.25 6.95 13.25H11.05C14.198 13.25 16.75 15.802 16.75 18.95C16.75 21.0487 15.0487 22.75 12.95 22.75H5.05C2.95132 22.75 1.25 21.0487 1.25 18.95ZM18.5303 6.46967C18.2374 6.17678 17.7626 6.17678 17.4697 6.46967C17.1768 6.76256 17.1768 7.23744 17.4697 7.53033L19.4393 9.5L17.4697 11.4697C17.1768 11.7626 17.1768 12.2374 17.4697 12.5303C17.7626 12.8232 18.2374 12.8232 18.5303 12.5303L20.5 10.5607L22.4697 12.5303C22.7626 12.8232 23.2374 12.8232 23.5303 12.5303C23.8232 12.2374 23.8232 11.7626 23.5303 11.4697L21.5607 9.5L23.5303 7.53033C23.8232 7.23744 23.8232 6.76256 23.5303 6.46967C23.2374 6.17678 22.7626 6.17678 22.4697 6.46967L20.5 8.43934L18.5303 6.46967Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconUserCross.isIcon = true;

export const IconUserCross = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconUserCross);
