// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconUserCircle(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M1.25 12C1.25 6.06294 6.06294 1.25 12 1.25C17.9371 1.25 22.75 6.06294 22.75 12C22.75 17.9371 17.9371 22.75 12 22.75C6.06294 22.75 1.25 17.9371 1.25 12ZM12 11C13.6569 11 15 9.65685 15 8C15 6.34315 13.6569 5 12 5C10.3431 5 9 6.34315 9 8C9 9.65685 10.3431 11 12 11ZM15.3333 18C16.2538 18 17 17.2538 17 16.3333V16.3333C17 14.4924 15.5076 13 13.6667 13H10.3333C8.49238 13 7 14.4924 7 16.3333V16.3333C7 17.2538 7.74619 18 8.66667 18H15.3333Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconUserCircle.isIcon = true;

export const IconUserCircle = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconUserCircle);
