// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSunrise(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M7 18C7 15.2386 9.23858 13 12 13C14.7614 13 17 15.2386 17 18M6 22H18M12 2L15 5M12 2L9 5M12 2V9M22 18L2 18M3.92896 9.92871L6.05028 12.05M17.9498 12.0498L20.0711 9.92848"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconSunrise.isIcon = true;

export const IconSunrise = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSunrise);
