// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconEuro(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M20.0002 6.0469C18.3249 4.17845 15.8738 3 13.1431 3C8.09364 3 4.00024 7.02944 4.00024 12C4.00024 16.9706 8.09364 21 13.1431 21C15.8738 21 18.3249 19.8216 20.0002 17.9531M2 10H12M2 14H10"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconEuro.isIcon = true;

export const IconEuro = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconEuro);
