// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./wallet.tsx";
export * from "./wallet-plus.tsx";
export * from "./wallet-move.tsx";
export * from "./wallet-minus.tsx";
export * from "./procent.tsx";
export * from "./procent-circle.tsx";
export * from "./pos.tsx";
export * from "./euro.tsx";
export * from "./euro-circle.tsx";
export * from "./dollar.tsx";
export * from "./dollar-circle.tsx";
export * from "./credit-card.tsx";
export * from "./credit-card-slash.tsx";
export * from "./credit-card-scan.tsx";
export * from "./credit-card-plus.tsx";
export * from "./credit-card-outcome.tsx";
export * from "./credit-card-minus.tsx";
export * from "./credit-card-income.tsx";
export * from "./cash.tsx";
