// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconProcent(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M6 2.24988C3.92893 2.24988 2.25 3.92881 2.25 5.99988C2.25 8.07095 3.92893 9.74988 6 9.74988C8.07107 9.74988 9.75 8.07095 9.75 5.99988C9.75 3.92881 8.07107 2.24988 6 2.24988ZM14.25 17.9999C14.25 15.9288 15.9289 14.2499 18 14.2499C20.0711 14.2499 21.75 15.9288 21.75 17.9999C21.75 20.0709 20.0711 21.7499 18 21.7499C15.9289 21.7499 14.25 20.0709 14.25 17.9999ZM18.6243 3.41606C18.854 3.07142 18.7609 2.60576 18.4163 2.376C18.0716 2.14624 17.606 2.23937 17.3762 2.58401L5.37621 20.584C5.14644 20.9287 5.23957 21.3943 5.58422 21.6241C5.92887 21.8538 6.39452 21.7607 6.62428 21.4161L18.6243 3.41606Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconProcent.isIcon = true;

export const IconProcent = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconProcent);
