// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconExport4(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M12 16V2M12 2L8 6M12 2L16 6M8 22H16C19.3137 22 22 19.3137 22 16V16C22 12.6863 19.3137 10 16 10H8C4.68629 10 2 12.6863 2 16V16C2 19.3137 4.68629 22 8 22Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconExport4.isIcon = true;

export const IconExport4 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconExport4);
