// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconLogIn3(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M2 12H17M17 12L13 8M17 12L13 16M15 22V22C18.866 22 22 18.866 22 15V9C22 5.13401 18.866 2 15 2V2C11.134 2 8 5.13401 8 9V15C8 18.866 11.134 22 15 22Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconLogIn3.isIcon = true;

export const IconLogIn3 = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconLogIn3);
