// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconClockSlash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M1 3.66667L2.69231 2L5.6663 4.92893M8.33333 3.03947C9.69277 2.37412 11.2251 2 12.8462 2C18.454 2 23 6.47715 23 12C23 13.5965 22.6201 15.1056 21.9445 16.4444M20.026 19.0711C18.1885 20.8807 15.6501 22 12.8462 22C7.23834 22 2.69231 17.5228 2.69231 12C2.69231 9.23858 3.82882 6.73858 5.6663 4.92893M20.026 19.0711L23 22M20.026 19.0711L5.6663 4.92893M20 1L23 4"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconClockSlash.isIcon = true;

export const IconClockSlash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconClockSlash);
