// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./timer.tsx";
export * from "./timer-2.tsx";
export * from "./timer-2-rec.tsx";
export * from "./time.tsx";
export * from "./stopwatch.tsx";
export * from "./stopwatch-slash.tsx";
export * from "./speed.tsx";
export * from "./speed-rec.tsx";
export * from "./history.tsx";
export * from "./history-rec.tsx";
export * from "./clock.tsx";
export * from "./clock-zzz.tsx";
export * from "./clock-slash.tsx";
export * from "./clock-plus.tsx";
export * from "./clock-minus.tsx";
export * from "./clock-cross.tsx";
export * from "./clock-check.tsx";
export * from "./calendar.tsx";
export * from "./calendar-plus.tsx";
export * from "./calendar-person.tsx";
export * from "./calendar-number.tsx";
export * from "./calendar-note.tsx";
export * from "./calendar-minus.tsx";
export * from "./calendar-event.tsx";
export * from "./calendar-dates.tsx";
export * from "./calendar-cross.tsx";
export * from "./calendar-arrow-right.tsx";
