// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconStopwatchSlash(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M8 4.93552C9.20496 4.33671 10.5632 4 12 4C14.4853 4 16.7353 5.00736 18.364 6.63604M20.0645 17C20.6633 15.795 21 14.4368 21 13C21 10.5147 19.9926 8.26472 18.364 6.63604M18.364 19.364C16.7353 20.9926 14.4853 22 12 22C7.02944 22 3 17.9706 3 13C3 10.5147 4.00736 8.26472 5.63604 6.63604M18.364 19.364L21 22M18.364 19.364L5.63604 6.63604M3 4L5.63604 6.63604M20.5 4.5L18.364 6.63604M14 1H10"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </svg>
  );
}

_IconStopwatchSlash.isIcon = true;

export const IconStopwatchSlash = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconStopwatchSlash);
