// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * as weather from "./weather";
export * as users from "./users";
export * as time from "./time";
export * as restaurant from "./restaurant";
export * as security from "./security";
export * as map from "./map";
export * as images from "./images";
export * as finances from "./finances";
export * as grid from "./grid";
export * as electronics from "./electronics";
export * as files from "./files";
export * as chat from "./chat";
export * as call from "./call";
export * as brands from "./brands";
export * as editor from "./editor";
export * as audiovisual from "./audiovisual";
export * as alerts from "./alerts";
export * as arrows from "./arrows";
export * as basic from "./basic";
