// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef } from "react";

export const IconUser = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(function IconUser(props) {
  return (
    <svg
      height="24"
      width="24"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={props.ref}
      {...props}
    >
      <path
        d="M8.75 6a3.25 3.25 0 116.5 0 3.25 3.25 0 01-6.5 0zM12 1.25a4.75 4.75 0 100 9.5 4.75 4.75 0 000-9.5zm-3.2 12a5.55 5.55 0 00-5.55 5.55 3.95 3.95 0 003.95 3.95h9.6a3.95 3.95 0 003.95-3.95 5.55 5.55 0 00-5.55-5.55H8.8zM4.75 18.8a4.05 4.05 0 014.05-4.05h6.4a4.05 4.05 0 014.05 4.05 2.45 2.45 0 01-2.45 2.45H7.2a2.45 2.45 0 01-2.45-2.45z"
        fillRule="evenodd"
      />
    </svg>
  );
});
