// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconDistributeVertically(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M3 1.25C2.58579 1.25 2.25 1.58579 2.25 2C2.25 2.41421 2.58579 2.75 3 2.75H21C21.4142 2.75 21.75 2.41421 21.75 2C21.75 1.58579 21.4142 1.25 21 1.25H3ZM3 21.25C2.58579 21.25 2.25 21.5858 2.25 22C2.25 22.4142 2.58579 22.75 3 22.75H21C21.4142 22.75 21.75 22.4142 21.75 22C21.75 21.5858 21.4142 21.25 21 21.25H3ZM5.16103 6.63148C5.90972 6.25 6.88982 6.25 8.85 6.25H15.15C17.1102 6.25 18.0903 6.25 18.839 6.63148C19.4975 6.96703 20.033 7.50247 20.3685 8.16103C20.75 8.90972 20.75 9.88982 20.75 11.85V12.15C20.75 14.1102 20.75 15.0903 20.3685 15.839C20.033 16.4975 19.4975 17.033 18.839 17.3685C18.0903 17.75 17.1102 17.75 15.15 17.75H8.85C6.88982 17.75 5.90972 17.75 5.16103 17.3685C4.50247 17.033 3.96703 16.4975 3.63148 15.839C3.25 15.0903 3.25 14.1102 3.25 12.15V11.85C3.25 9.88982 3.25 8.90972 3.63148 8.16103C3.96703 7.50247 4.50247 6.96703 5.16103 6.63148Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconDistributeVertically.isIcon = true;

export const IconDistributeVertically = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconDistributeVertically);
