// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconSliderHorizontal(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M7.43404 2.68597C8.28968 2.25 9.40979 2.25 11.65 2.25H12.35C14.5902 2.25 15.7103 2.25 16.566 2.68597C17.3186 3.06947 17.9305 3.68139 18.314 4.43404C18.75 5.28968 18.75 6.40979 18.75 8.65V15.35C18.75 17.5902 18.75 18.7103 18.314 19.566C17.9305 20.3186 17.3186 20.9305 16.566 21.314C15.7103 21.75 14.5902 21.75 12.35 21.75H11.65C9.40979 21.75 8.28968 21.75 7.43404 21.314C6.68139 20.9305 6.06947 20.3186 5.68597 19.566C5.25 18.7103 5.25 17.5902 5.25 15.35V8.65C5.25 6.40979 5.25 5.28968 5.68597 4.43404C6.06947 3.68139 6.68139 3.06947 7.43404 2.68597ZM2.75 4C2.75 3.58579 2.41421 3.25 2 3.25C1.58579 3.25 1.25 3.58579 1.25 4V20C1.25 20.4142 1.58579 20.75 2 20.75C2.41421 20.75 2.75 20.4142 2.75 20V4ZM22.75 4C22.75 3.58579 22.4142 3.25 22 3.25C21.5858 3.25 21.25 3.58579 21.25 4V20C21.25 20.4142 21.5858 20.75 22 20.75C22.4142 20.75 22.75 20.4142 22.75 20V4Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconSliderHorizontal.isIcon = true;

export const IconSliderHorizontal = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconSliderHorizontal);
