// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

import React, { forwardRef, ForwardedRef } from "react";

function _IconTransform(
  { className, ...props }: React.SVGProps<SVGSVGElement>,
  ref: ForwardedRef<SVGSVGElement>,
) {
  return (
    <svg
      height="24"
      width="24"
      fill="none"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      ref={ref}
      className={["icon", className].join(" ")}
      {...props}
    >
      <path
        d="M15.325 4.25C15.6725 2.53832 17.1858 1.25 19 1.25C21.0711 1.25 22.75 2.92894 22.75 5C22.75 6.81422 21.4617 8.32754 19.75 8.67499L19.75 15.325C21.4617 15.6725 22.75 17.1858 22.75 19C22.75 21.0711 21.0711 22.75 19 22.75C17.1858 22.75 15.6725 21.4617 15.325 19.75L8.67499 19.75C8.32753 21.4617 6.81422 22.75 5 22.75C2.92893 22.75 1.25 21.0711 1.25 19C1.25 17.1858 2.53832 15.6725 4.25 15.325L4.25 8.67499C2.53832 8.32754 1.25 6.81422 1.25 5C1.25 2.92894 2.92893 1.25 5 1.25C6.81422 1.25 8.32753 2.53832 8.67499 4.25L15.325 4.25ZM15.325 5.75L8.67499 5.75C8.37672 7.21935 7.21935 8.37673 5.75 8.67499L5.75 15.325C7.21935 15.6233 8.37672 16.7807 8.67499 18.25L15.325 18.25C15.6233 16.7807 16.7807 15.6233 18.25 15.325L18.25 8.67499C16.7807 8.37673 15.6233 7.21935 15.325 5.75Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
}

_IconTransform.isIcon = true;

export const IconTransform = forwardRef<
  SVGSVGElement,
  React.SVGProps<SVGSVGElement>
>(_IconTransform);
