name: "Build"
on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run Build
        run: yarn run build
