name: "Eslint"
on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn run build
      - name: Run ESLint
        run: yarn run lint
