// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./comments.tsx";
export * from "./comments-2.tsx";
export * from "./comment.tsx";
export * from "./comment-text.tsx";
export * from "./comment-slash.tsx";
export * from "./comment-plus.tsx";
export * from "./comment-minus.tsx";
export * from "./comment-dots.tsx";
export * from "./comment-check.tsx";
export * from "./comment-cancel.tsx";
export * from "./comment-alert.tsx";
export * from "./comment-2.tsx";
export * from "./comment-2-text.tsx";
export * from "./comment-2-slash.tsx";
export * from "./comment-2-question.tsx";
export * from "./comment-2-plus.tsx";
export * from "./comment-2-minus.tsx";
export * from "./comment-2-info.tsx";
export * from "./comment-2-dots.tsx";
export * from "./comment-2-check.tsx";
export * from "./comment-2-cancel.tsx";
export * from "./comment-2-alert.tsx";
