// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

// ⚠️ DO NOT EDIT MANUALLY ⚠️
// this file is auto-generated by scripts/gen-icons.ts

export * from "./voicemail.tsx";
export * from "./phone.tsx";
export * from "./dialpad.tsx";
export * from "./call-slash.tsx";
export * from "./call-remove.tsx";
export * from "./call-redirected.tsx";
export * from "./call-received.tsx";
export * from "./call-outgoing.tsx";
export * from "./call-on-hold.tsx";
export * from "./call-muted.tsx";
export * from "./call-missed.tsx";
export * from "./call-incoming.tsx";
export * from "./call-end.tsx";
export * from "./call-decline.tsx";
export * from "./call-calling.tsx";
export * from "./call-add.tsx";
